- CustomScript/customscript.py
- CustomScript/test/HandlerEnvironment.json
- CustomScript/test/MockUtil.py
- CustomScript/test/test_preprocess_file.py
- CustomScript/test/test_run_script.py
1.Preprocess the text file. If it is a binary file, skip it.
Then converting text files from DOS to Unix formats
remove BOM for 'UTF-8', 'UTF-16LE', 'UTF-16BE'
2.retry download
> Customscript v1.3

- VMAccess/README.md
1. Add Azure CLI Sample
2. Add the syntaxes in ARM mode
3. Add the json sample for ARM template
4. Refine the format
> Update the documents for VMAccess Extension

- CustomScript/README.md
1. Add Azure CLI Sample
2. Add the syntaxes in ARM mode
3. Add the json sample for ARM template
4. Refine the format
> Update the documents for CustomScript Extension

- OSPatching/README.md
1. Add Azure CLI Sample
2. Add the syntaxes in ARM mode
3. Add the json sample for ARM template
4. Refine the format
> Update the documents for OSPatching Extension

- VMBackup/main/backuplogger.py
- VMBackup/main/fsfreezer.py
add support for the pageblob log.
> add support for the pageblob log.

- CustomScript/HandlerManifest.json
- CustomScript/README.md
- CustomScript/customscript.py
- Utils/HandlerUtil.py
1. Enhance retry logic and add internal DNS check in case of network failure
2. Change permission of extension log path to enhance security
3. Remove syslog handler from Utils
> Refine CustomScript Extension

- VMAccess/HandlerManifest.json
- VMAccess/vmaccess.py
Yue, could you please review? This is new functionality that has been requested.
> Adding Check and Repair disk to VMAccessExtension

- OSPatching/patch/AbstractPatching.py
1. Move syslogger from Utils to OSPatching
2. Add a retry queue for downloading patches
> Enhance ospatching

- CustomScript/README.md
- DSC/README.md
- OSPatching/README.md
- VMAccess/README.md
> Add the links of ARM template samples into README.md

- RDMAUpdate/main/patch/SuSEPatching.py
fix two issues:
1. reboot after rdma driver is installed
2. use search to find the nd driver version, to deal with the possible situation where multiple values are defined in KVP pool0
> reboot after rdma package is installed

- VMAccess/README.md
- VMAccess/vmaccess.py
Squash all the commits into a single one, and create a PR on behalf of Snesha
> Updating fsck_repair

- Common/WALinuxAgent-2.0.16/waagent
- VMAccess/HandlerManifest.json
- VMAccess/README.md
- VMAccess/references
VMAccess enable failed after Oracle kernel update (6&7) whose distro name is oracle not redhat.
waagent(2.0.16) can fix it.
> Bumped waagent from 2.0.14 to 2.0.16

- VMAccess/README.md
1. Support both ssh-rsa and .pem format
2. Add an scenario about how to add a new account with a ssh key
Close #94
> Fix the error in setting "ssh_key" parameter

- CustomScript/README.md
Just remove a double negation that, to my mind, didn't make sense
> Some typo corrections

- CustomScript/HandlerManifest.json
- CustomScript/README.md
- CustomScript/customscript.py
1. Do not log the command to execute if it's protected
2. Add the uris which it fails to download using MDS events
> Refine logs and MDS events

- docs/handler-registration.md
- docs/sample-extension.md
> Fix some spelling error

- docs/handler-registration.md
Add details for the azure extension publishing cert
> Add details for the azure extension publishing cert

- Diagnostic/diagnostic.py
@LiweiPeng & @jasonzio : Please review this PR. Thanks.
> #128 [LAD] LAD should restart OMI if it crashes

- Diagnostic/diagnostic.py
- OMI install is retried (up to 3 times) if it fails to install.
- OMI is uninstalled when LAD is uninstalled.
> [LAD] OMI install/uninstall changes

- Diagnostic/diagnostic.py
@jasonzio @LiweiPeng : Please take one more last look at this. Fully tested for OMI crashing cases & also uninstall/reinstall cases. Fixed a few minor logging issues as well. Once this is approved, I'll go ahead and release LAD v.2.3.9. Thanks.
> [LAD] OMI restart logic improvement, minor logging fixes

- Diagnostic/diagnostic.py
Addressing Issue #135. @LiweiPeng & @jasonzio, please review.
> [LAD] syslog messages are not collected on SLES 11 by default

- Diagnostic/diagnostic.py
@LiweiPeng, please review. Thanks.
> [LAD] Fix 'enableSyslog' config property name

- Diagnostic/diagnostic.py
@LiweiPeng : Please review. This is a fix for #139 . Thanks.
> [LAD] Shouldn't always kill mdsd process by 'kill -9'

- Diagnostic/diagnostic.py
- Diagnostic/rsyslog5/omazurelinuxmds.conf
- Diagnostic/rsyslog7/omazurelinuxmds.conf
- Diagnostic/rsyslog8/omazurelinuxmds.conf
@jasonzio @LiweiPeng - Please review this PR. I'm aiming at releasing LAD 2.3.9001 after this PR.
> [LAD] Add OMI diag dump code, enable core dump

- Diagnostic/diagnostic.py
@jasonzio @LiweiPeng - Please review this.
Not knowing semanage is not installed by default on Redhat, I removed the policycoreutils-python install step, which caused syslog collection to stop working on Redhat-based distros. It's a good thing that this caught the potential issue of broken syslog collection when a randomly available port was assigned. That potential issue is also fixed here as well.
> [LAD] Fix broken syslog collection on Redhat

- VMBackup/main/DiskUtil.py
- VMBackup/main/HttpUtil.py
- VMBackup/main/common.py
- VMBackup/main/fsfreezer.py
- VMBackup/main/handle.py
- VMBackup/main/snapshotter.py
@ahmetalpbalkan I have removed the piece of code where it was creating the config file. Also the config file path and name changed to '/etc/azure/vmbackup.conf'
> Freeze issue

- CustomScript/customscript.py
> Fix casing in error message to be consistent.

- .gitignore
- CustomScript/CHANGELOG.md
- CustomScript/README.md
- README.md
Move all version information out of README.md because it becomes stale
quickly.
Closes #145.
Closes #147.
> Use a change log.

- Diagnostic/ChangeLogs
- Diagnostic/README.md
- Diagnostic/diagnostic.py
- Diagnostic/manifest.xml
@jasonzio @LiweiPeng - Please review.
ChangeLogs:
2016-06-21: LAD-2.3.9003
- Monitoring agent (mdsd) updates for a memory issue fix, a signal handler fix,
and a fix to avoid a spin loop under certain circumstances
- doesn't count non-quick crashes (>30 mins) towards retry limit
- OMI reconfiguration not to listen to port 1270
- Use systemd on Ubuntu 16.04 as well
- Validate mdsd XML config before starting mdsd, fails fast on invalid
config (with success)
- Small Python 2.6 bug fix (syslog.openlog())
> Merge LAD v.2.3.9003 changes to master for release

- Diagnostic/ChangeLogs
- Diagnostic/README.md
- Diagnostic/diagnostic.py
- Diagnostic/manifest.xml
@LiweiPeng - Please review. Thanks.
> [LAD] Merge 2.3.9005 release branch to master

- Diagnostic/ChangeLogs
- Diagnostic/README.md
- Diagnostic/diagnostic.py
- Diagnostic/manifest.xml
- Diagnostic/rsyslog5/omazurelinuxmds.conf
- Diagnostic/rsyslog7/omazurelinuxmds.conf
- Diagnostic/rsyslog8/omazurelinuxmds.conf
> [LAD] Merge release branch to master for 2.3.9007 release

- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/handle.py
> Removing Distro Info

- Diagnostic/diagnostic.py
- Diagnostic/portal.xml.template
> Unpivot PercentIdleTime. Fetch storage endpoint correctly.

- Diagnostic/diagnostic.py
> Kali Linux 2016.2 Support

- CustomScript/README.md
- CustomScript/manifest.xml
> customscript: update docs/manifest with new version

- Diagnostic/Utils/XmlUtil.py
- Diagnostic/diagnostic.py
@jasonzio , @LiweiPeng - Please review.
> [LAD] Fix Events/OMI xml cfg regression on Python 2.6-based distros

- VMBackup/main/DiskUtil.py
- VMBackup/main/HttpUtil.py
- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/Utils/Status.py
- VMBackup/main/handle.py
- VMBackup/main/patch/AbstractPatching.py
- VMBackup/main/patch/centosPatching.py
- VMBackup/main/patch/redhatPatching.py
--Status Object created
-- telemetery added
-- Common Status JSON string is generated
-- Handled lsblk path
> Creating Status Object and Adding telemetery

- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/handle.py
@vityagi @bpramod please review
> status file changes

- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/Utils/Status.py
- VMBackup/main/handle.py
Added more fields in status object
-unique machine Id
- total used space
- number of mounts 
- flags to assure the computation
> Storage Details Computation

- VMEncryption/MANIFEST.in
- VMEncryption/VMEncryption.pyproj
- VMEncryption/main/Common.py
- VMEncryption/main/DiskUtil.py
- VMEncryption/main/ExtensionParameter.py
- VMEncryption/main/KeyVaultUtil.py
- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/ubuntu_1404/Ubuntu1404EncryptionStateMachine.py
- VMEncryption/main/oscrypto/ubuntu_1404/__init__.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptpatches/ubuntu_1404_initramfs.patch
- VMEncryption/main/oscrypto/ubuntu_1404/encryptscripts/azure_crypt_key.sh
- VMEncryption/main/oscrypto/ubuntu_1404/encryptscripts/inject_luks_header.sh
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/EncryptBlockDeviceState.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/PrereqState.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/SelinuxState.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/SplitRootPartitionState.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/StripdownState.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/UnmountOldrootState.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/__init__.py
- VMEncryption/main/patch/SuSEPatching.py
- VMEncryption/main/patch/UbuntuPatching.py
- VMEncryption/main/patch/redhatPatching.py
- VMEncryption/setup.py
- Always report up-to-date status of OS and data drives in substatus messages, in order to enable quick status fetching in azure-powershell [PR 3112](https://github.com/Azure/azure-powershell/pull/3112)
- Add support for OS disk encryption for Ubuntu 14
- Add support for AAD client cert auth
> Disk encryption for Linux November release

- Diagnostic/ChangeLogs
- Diagnostic/README.md
- Diagnostic/diagnostic.py
- Diagnostic/manifest.xml
@jasonzio @LiweiPeng : Please review. E2E tests passed on our Jenkins EDP.
> [LAD] 2.3.9013 release PR

- VMBackup/main/HttpUtil.py
- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/Utils/Status.py
- VMBackup/main/blobwriter.py
- VMBackup/main/handle.py
- VMBackup/main/parameterparser.py
- VMBackup/main/snapshotter.py
Managed disk VM Backup changes
> Managed disk VM Backup changes

- Diagnostic/ChangeLogs
- Diagnostic/README.md
- Diagnostic/Utils/XmlUtil.py
- Diagnostic/diagnostic.py
- Diagnostic/manifest.xml
- Diagnostic/mdsdConfig.xml.template
@jasonzio , @LiweiPeng : Please review. Thanks.
> LAD 2.3.9015 release PR

- VMBackup/main/common.py
- VMBackup/main/handle.py
- VMBackup/main/snapshotter.py
FailedRetryableSnapshotFailedRestrictedNetwork,FailedRetryableSnapshotFailedNoNetwork,FailedRetryableFsFreezeFailed Error codes added
> adding FailedRetryableSnapshotFailedRestrictedNetwork Error code

- Diagnostic/ChangeLogs
- Diagnostic/diagnostic.py
- Diagnostic/manifest.xml
@jasonzio , @LiweiPeng : Please review. Thanks.
> Lad 2.3.9017 release PR

- VMBackup/main/ExtensionErrorCodeHelper.py
- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/Utils/Status.py
- VMBackup/main/handle.py
- VMBackup/main/snapshotter.py
> Managed disk

- Diagnostic/ChangeLogs
- Diagnostic/README.md
- Diagnostic/diagnostic.py
- Diagnostic/manifest.xml
@jasonzio , @LiweiPeng : Please review. Thanks.
> Lad 2.3.9019

- Diagnostic/diagnostic.py
@jasonzio @LiweiPeng : Please review. Not sure why Liwei doesn't show up when I try to enter him in the "Reviewers"...
> [LAD] Self-mitigate potential mdsd memory leaking

- Diagnostic/Utils/imds_util.py
- Diagnostic/diagnostic.py
- Diagnostic/watcherutil.py
> [LAD] IMDS probe feature informational PR

- VMBackup/main/ExtensionErrorCodeHelper.py
- VMBackup/main/PluginHost.conf
- VMBackup/main/PluginHost.py
- VMBackup/main/ScriptRunner.py
- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/common.py
- VMBackup/main/handle.py
- VMBackup/main/tempPlugin/PluginConfig.json
- VMBackup/main/tempPlugin/PluginHost.conf
- VMBackup/main/tempPlugin/postScript.sh
- VMBackup/main/tempPlugin/preScript.sh
- VMBackup/main/tempPlugin/vmbackup.conf
- VMBackup/setup.py
- Adding new error Codes for Linux
- Handling Permissions of scripts and config files
- Changes in Health Model
> Linux App Consistent Backup

- DSC/Makefile
- DSC/dsc.py
- DSC/manifest.xml
1) Improved the tracing in DSC to debug/troubleshoot customer issues
2) Fixed few issues to exclude in score card where customer enters incorrect input.
> Changes to DSC Linux extension

- Diagnostic/Utils/imds_util.py
> [LAD] Apply IMDS API change

- DSC/HandlerManifest.json
- DSC/dsc.py
- DSC/manifest.xml
- DSC/test/test_compare_pkg_version.py
OMI is being used in OMSAgent, Asm Extensions. Added a version comparison check before upgrading OMI.
> DSCForLinux - Fixed the OMS version conflict with other extensions

- VMBackup/HandlerManifest.json
- VMBackup/main/ExtensionErrorCodeHelper.py
- VMBackup/main/PluginHost.py
- VMBackup/main/ScriptRunner.py
- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/Utils/WAAgentUtil.py
- VMBackup/main/common.py
- VMBackup/main/handle.py
- VMBackup/main/snapshotter.py
- VMBackup/setup.py
- fixing missing decryption certificate
- adding App Name to the telemetry
- adding python version
- fixing bug sequential snapshotting
-
> Fixing missing decryption certificate

- VMBackup/setup.py
> Add MediaLink element

- DSC/README.md
- DSC/dsc.py
- DSC/manifest.xml
- DSC/test/test_register.py
Added more tracing for enable functionality.
> DSCForLinux

- Diagnostic/tests/lad_2_3_compatible_portal_pub_settings.json
- Diagnostic/tests/test_builtin.py
> Fix "local" keys to read "locale"

- OSPatching/patch/AbstractPatching.py
This fixes bugs where scheduled times in cron jobs aren't calculated properly. It also ensures Sunday is written as 0 instead of 7 for the day-of-week field.
Fixes #348
> Fixing rollover bugs in scheduled OSPatch tasks

- DSC/dsc.py
- DSC/manifest.xml
- DSC/test/MockUtil.py
- DSC/test/status/0.status
- DSC/test/test_status_update.py
Made changes to update status file with Node id and VMUUID after successful enable operation.@weijiel, please review
> DSCForLinux: Updated status file with nodeid and VMUUID

- VMBackup/HandlerManifest.json
- VMBackup/main/ScriptRunner.py
- VMBackup/main/Utils/DiskUtil.py
- VMBackup/main/Utils/SizeCalculation.py
- VMBackup/main/fsfreezer.py
- VMBackup/main/handle.py
- VMBackup/manifest.xml
- VMBackup/setup.py
- VMBackup/testmanifest.xml
-> PrePost - Run Post-script even if Pre-script had failed/timed-out
-> handling the FSFreexe binary strucking
-> Changing the names of manifest file
-> handling df output for older distros
> Changes for 1708 work items

- OSPatching/README.md
- OSPatching/handler.py
Adding log message to help raise awareness to customers
> OSPatching deprecation

- Diagnostic/ChangeLogs
- Diagnostic/README.md
- Diagnostic/Utils/lad_logging_config.py
- Diagnostic/manifest.xml
Revert an incompletely tested change inadvertently pushed to master.
> Revert use of sudo_tail

- RDMAUpdate/main/Utils/HandlerUtil.py
- TestHandlerLinux/resources/HandlerUtil.py
- Utils/HandlerUtil.py
- VMAccess/manifest.xml
- VMAccess/vmaccess.py
Create telemetry events for the scenarios executed by VMAccess.
> vmaccess: do not refer to temp files by name

- VMEncryption/main/Common.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/centos_68/encryptstates/PrereqState.py
- VMEncryption/main/patch/centosPatching.py
> Fix centos patches

- OmsAgent/Fairfax/omsagent_ff.py
- OmsAgent/README.md
- OmsAgent/omsagent.py
Add OneClick-specific errors
Fairfax endpoints and code may have to be altered slightly when Fairfax OneClick support is implemented
Retry OMS request in case of 202 or 204
Improve error grouping
ARM and Classic VMs have both been tested
> OmsAgent: Supplement Enable for OneClick experience

- VMEncryption/main/Common.py
- VMEncryption/main/DiskUtil.py
- VMEncryption/main/ExtensionParameter.py
- VMEncryption/main/handle.py
Allow users to encrypt-format their disks for faster performance.
> VMEncryption: Adds Encrypt Format feature

- OmsAgent/Fairfax/omsagent_ff.py
- OmsAgent/omsagent.py
- Setting the flag to remove workspace configuration on update
- Removing all the files and subfolders of workspace under the agent etc & var 
@NarineM
> OMS Agent ASC - remove workspace configuration from the box on uninstall

- VMEncryption/main/Common.py
- VMEncryption/main/handle.py
Fix issue identified in precheck logic - https://github.com/ejarvi/azure-linux-extensions/issues/4
> fix CheckUtil syntax

- OmsAgent/omsagent.py
Update the bundle version from 1.4.1-123 to 1.4.4-210 and Fix the remove_workspace_configuraton method to work properly and run on uninstall except for 'upgrade'.
> Update bundle version to 1.4.4.210 and fix the remove workspace config on Uninstall

- OmsAgent/Fairfax/omsagent_ff.py
- OmsAgent/omsagent.py
Changing OMS agent extension enable() error code 20 to not conflict with that of install() of installer script.
@NarineM
> Changing OMS agent extension enable() error code 20 to not conflict with that of install()

- OmsAgent/Fairfax/omsagent_ff.py
…g method
fix the remove workspace config method
update IsUpgradeWorkspaceConfiguration to IsUpgrade for remove workspace config method
In omsagent_ff.py: Update bundle version to 1.4.4-210 and fix the remove workspace config method
> In omsagent_ff: Update bundle version to 1.4.4.210 and fix the remove workspace configuration

- VMEncryption/main/Common.py
- VMEncryption/main/handle.py
report a transitioning state prior to encryption for proper synchronization with host
> add transitioning state

- Diagnostic/diagnostic.py
changed log message in response to following issue: https://github.com/Azure/azure-linux-extensions/issues/519
> changed the extension name in LAD startup log message to LinuxDiagnostic

- VMEncryption/main/Common.py
- VMEncryption/main/DiskUtil.py
replaces lsblk --json syntax with pkname parsing for backwards compatibility with older versions of lsblk
> fix lsblk --json issue 

- OmsAgent/omsagent.py
> Add ubuntu 18.04 to list of supported distros

- VMEncryption/main/Common.py
- VMEncryption/main/DiskUtil.py
- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/rhel_72/encryptstates/PrereqState.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PrereqState.py
- VMEncryption/main/patch/SuSEPatching.py
- VMEncryption/main/patch/UbuntuPatching.py
- VMEncryption/main/patch/centosPatching.py
- VMEncryption/main/patch/redhatPatching.py
- VMEncryption/test/test_DiskUtil.py
- include os disk in per disk encryption settings
- unblock centos 7.4, rhel 7.4, and rhel 7.5 
- remove dead code related to adal
- fix lsblk issue on ubuntu 14.04
> single pass linux extension updates

- DSC/Makefile
- DSC/dsc.py
- DSC/manifest.xml
Made changes to fix Debian distro issues
> DSCForLinux - Debian changes

- VMBackup/main/Utils/HostSnapshotObjects.py
- VMBackup/main/Utils/Status.py
- VMBackup/main/WaagentLib.py
- VMBackup/main/common.py
- VMBackup/main/freezesnapshotter.py
- VMBackup/main/guestsnapshotter.py
- VMBackup/main/hostsnapshotter.py
- VMBackup/main/parameterparser.py
- VMBackup/manifest.xml
- VMBackup/prodmanifest.xml
- Host Plugin 1.5 changes
- assigning FailedSnapshotLimitReached errorcode
> Host Plugin 1.5 changes

- OmsAgent/watcherutil.py
@abhijeetgaiha Here is the requested change from #619
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/azure-linux-extensions/620)
> Remove extra backslash from telemetry message

- VMBackup/main/handle.py
- VMBackup/main/parameterparser.py
- VMBackup/manifest.xml
- VMBackup/prodmanifest.xml
Tested the changes using updated BCM for unmanaged VMs
> Using new CRP & BCM contract

- OmsAgent/omsagent.py
- OmsAgent/watcherutil.py
It adds two self monitoring features
1. Monitor heartbeat and specific error logs from oms agent logs
2. Monitor for resource usage of the agent
> OMS agent self monitoring feature

- Common/WALinuxAgent-2.0.16/waagent
- CustomScript/customscript.py
- CustomScript/manifest.xml
- Utils/HandlerUtil.py
- Utils/LogUtil.py
- Utils/ScriptUtil.py
Python2/Python3 support for CustomScript extention for Linux
> Python2/Python3 support for CustomScript extention for Linux

- VMEncryption/main/Common.py
- VMEncryption/main/DiskUtil.py
- VMEncryption/main/EncryptionSettingsUtil.py
- VMEncryption/main/ResourceDiskUtil.py
- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/main/handle.py
Various fixed for ADE singlepass
- transitioning fix
- fix to disable encryption
- fix to encryption substatus reporting
- fix synchronization issue that was causing 500 errors from the wire server
> ADE SinglePass fixes

- Common/WALinuxAgent-2.0.16/waagent
- VMAccess/manifest.xml
- VMAccess/test/env.py
- VMAccess/test/test_iptable_rules.py
- VMAccess/test/test_reset_account.py
- VMAccess/test/test_reset_sshd_config.py
- VMAccess/vmaccess.py
Minor fixes in VMAccess and WAAgent to support Python2 and 3.
> Python2/Python3 support for VMAccess extension for Linux

- VMAccess/HandlerManifest.json
- VMAccess/extension_shim.sh
- VMAccess/manifest.xml
- VMAccess/vmaccess.py
Added a new Shell script to find the correct python version and invoke the extension script.
FYI: @narrieta, @boumenot, @roiyz-msft.
> Adding a shell layer to find python version on the box

- CustomScript/HandlerManifest.json
- CustomScript/customscript.py
- CustomScript/manifest.xml
- CustomScript/shim.sh
- Adding shim layer for CSE
- Bumping version to 1.5.4
> CustomScriptExtension shim layer for python interpreter

- VMEncryption/main/BekUtil.py
- VMEncryption/main/Common.py
- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/centos_68/encryptpatches/centos_68_dracut.patch
- VMEncryption/main/oscrypto/rhel_68/encryptpatches/rhel_68_dracut.patch
- VMEncryption/main/oscrypto/rhel_72/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptscripts/azure_crypt_key.sh
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/UnmountOldrootState.py
- VMEncryption/main/oscrypto/ubuntu_1604/encryptscripts/azure_crypt_key.sh
- VMEncryption/main/oscrypto/ubuntu_1604/encryptstates/UnmountOldrootState.py
- VMEncryption/main/patch/SuSEPatching.py
- VMEncryption/main/patch/UbuntuPatching.py
- VMEncryption/main/patch/centosPatching.py
- VMEncryption/main/patch/redhatPatching.py
- move time consuming operations to enable 
- remove dead code and unnecessary packages
> ADE SP QOS Improvements

- VMEncryption/main/Common.py
- VMEncryption/main/handle.py
- move package install under daemon process to minimize guest agent timeout risk
> ADE SP QOS timeout fix 

- VMEncryption/main/BekUtil.py
- VMEncryption/main/Common.py
- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/centos_68/encryptpatches/centos_68_dracut.patch
- VMEncryption/main/oscrypto/rhel_68/encryptpatches/rhel_68_dracut.patch
- VMEncryption/main/oscrypto/rhel_72/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptscripts/azure_crypt_key.sh
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/UnmountOldrootState.py
- VMEncryption/main/oscrypto/ubuntu_1604/encryptscripts/azure_crypt_key.sh
- VMEncryption/main/oscrypto/ubuntu_1604/encryptstates/UnmountOldrootState.py
- VMEncryption/main/patch/UbuntuPatching.py
- VMEncryption/main/patch/centosPatching.py
- VMEncryption/main/patch/redhatPatching.py
ADE Dual Pass QOS improvements in this PR include: 
- move extra package installs to the enable stage to eliminate risk of install timeouts 
- remove unused NTFS package and related calls since key volume is always vfat 
- add stderr logging for better diagnostics as a stepping stone to future QOS improvements 
- include active directory authentication library and dependencies still required for dual pass KV ops
> ADE DP QOS Improvements

- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/Utils/SizeCalculation.py
- VMBackup/main/common.py
- VMBackup/main/freezesnapshotter.py
- VMBackup/main/handle.py
> Handling network shares

- OmsAgent/extension-test/VMRunScript.py
- OmsAgent/extension-test/omsData.py
- OmsAgent/extension-test/omsExtensionTest.py
- OmsAgent/extension-test/omsStatusCheck.py
Adding the scripts for the Oms Extension release testing.
Note: Still have to add,
1. Fake MySQL logs & unique VM name generator
2. Add Verify_e2e.py script - @hestolz
3. Azure Key Vault for sensitive variables
> Oms Extension test automation scripts

- VMBackup/main/common.py
- VMBackup/main/freezesnapshotter.py
- VMBackup/main/parameterparser.py
•	Switching to GuestOnly mode if any disk is excluded.
•	Having the LUN list ready for sending to Host.
•	Testing has not been done yet.
> Consuming the new extension contract

- VMBackup/main/freezesnapshotter.py
Setting IsAnySnapshotFailed to false when success
> Setting IsAnySnapshotFailed to false when success

- Diagnostic/manifest.xml
> LAD release 3.0.119

- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/patch/__init__.py
code changes to support suse 15
> changes for SUSE 15

- CustomScript/shim.sh
> nit; Python3 not correctly called

- VMEncryption/main/Common.py
- increment version number prior to deployment
> increment version to 1.1.0.25

- OmsAgent/Fairfax/omsagent_ff.py
- OmsAgent/Mooncake/omsagent_mc.py
- OmsAgent/omsagent.py
- new error in install success rate with python3 where octal number representation is different
https://dataexplorer.azure.com/clusters/azlinux/databases/AzureLinux?query=H4sIAAAAAAAAA6WRwUrDQBCG74LvMN2TQkkNkoNChFIiCI09RHrf7k7Slc1O2NnVHHwYn8UnMypJe/BQKHP7559v/mGKPqBjQ654Qxd4ewuXFx/wvkeP8CxbzHNRGuWJqQ5J4QL6zhvGlaWok5KcCeSNa5JNy8tmIDySXxsXewHSadh06GUY6JDnIJ4cB2mtOGx4MS1WQbYdPIBs6CrT1zD2/p+d2isbeUgzy8VB26LncSBN7pL0aNWEq6JSyPxjqqVl/A1aDopsEGaKXJDGMQhWPu52qI8Yk2svBwP2JoAijfeQpQK+Pv8KFgvslY0aNdSeWqjWyxMQ6c3ZiCw7P8UJh3SeXlGFETI/fHE+fuUbFSDep1YCAAA=
> octal number format for python3

- Diagnostic/manifest.xml
> Increment version for LAD's Feb release

- VMEncryption/main/check_util.py
- VMEncryption/test/test_check_util.py
- add vfat module check to precheck
> ADE SP March QOS

- VMEncryption/main/Common.py
- VMEncryption/main/check_util.py
- VMEncryption/main/handle.py
- VMEncryption/main/patch/UbuntuPatching.py
- VMEncryption/test/test_check_util.py
1. Fail OS encryption if memory less than 7 GB
2. Do apt-get update only when install fails
> ADE DP March QoS

- VMBackup/main/ExtensionErrorCodeHelper.py
- VMBackup/main/HttpUtil.py
- VMBackup/main/WaagentLib.py
- VMBackup/main/common.py
- VMBackup/main/freezesnapshotter.py
- VMBackup/main/fsfreezer.py
- VMBackup/main/handle.py
- VMBackup/main/hostsnapshotter.py
- VMBackup/manifest.xml
- VMBackup/prodmanifest.xml
Resolving the bug for Suse 15 machines where system calls are failing to fetch distro information. 
assigning FailedRetryableSnapshotRateExceeded error code
Code refactored by making error code assigning common for guest and host snapshotting flow
disambiguation of crashes in host flow with new telemetry error code (558)
added VM architecture info to telemetry
> 1903 changes

- VMBackup/main/freezesnapshotter.py
- VMBackup/prodmanifest.xml
resolving bug after refactoring in firstGuestThenHost mode
> changes for HotFix

- OmsAgent/omsagent.py
- send more output data besides exit code for better debugging of failures
> add output to extension logs sent back to WAAgent

- VMEncryption/main/CommandExecutor.py
- VMEncryption/main/handle.py
- VMEncryption/main/patch/UbuntuPatching.py
- VMEncryption/test/test_command_executor.py
Timeout and fail if apt-get update does not complete in 30 seconds.
Please provide feedback on 30 sec timeout for apt-get update.
> Timeout apt-get update if it is taking more time than expected

- VMEncryption/main/CommandExecutor.py
- VMEncryption/main/handle.py
- VMEncryption/main/patch/UbuntuPatching.py
- VMEncryption/test/test_command_executor.py
Timeout and fail if apt-get update does not complete in 30 seconds.
Please provide feedback on 30 sec timeout for apt-get update.
> Timeout apt-get update if it is taking more time than expected[DualPass]

- DSC/README.md
- DSC/dsc.py
Includes the following changes to improve our error handling during Install:
- Check for whether the Distro is supported, if not report back an error
- Check whether dpkg is locked and perform a retry of the command if it is.
- Updated our supported distros in the README
> June 2019 Changes for Linux DIY Dsc Extension Release

- VMEncryption/main/BekUtil.py
- VMEncryption/main/EncryptionConfig.py
- VMEncryption/main/handle.py
Disable encryption is updated to do the following:
1. Backup azure_crypt_params.ini at end of decryption
2. Delete passphrase file at end of decryption
3. Refactor the function to remove the reboot
> Do proper cleanup after successful decryption operation.

- OmsAgent/HandlerManifest.json
- OmsAgent/manifest.xml
- OmsAgent/omsagent.py
- OmsAgent/watcherutil.py
Updated versions for omsagent 1.11.11 extension release
> Nidhanda patch 1

- OmsAgent/extension-test/omsfiles/oms_extension_run_script.py
> Syntax fix in oms_extension_run_script.py

- VMBackup/main/HttpUtil.py
- VMBackup/main/common.py
- VMBackup/main/hostsnapshotter.py
Skipping Proxy for all HTTP calls.
It is added as a configurable value.
> skipping proxy

- VMEncryption/main/Common.py
- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/main/handle.py
- VMEncryption/test/test_handler_util.py
- make parsing of settings files more robust in various scenarios
> ADE dual pass settings parsing 

- VMEncryption/main/SupportedOS.json
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/rhel_72/encryptstates/PrereqState.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PrereqState.py
Add support for CentOS 7.7 and RHEL 7.7 to ADE dual pass extension
> ADE DP - Add CentOS 7.7 and RHEL 7.7 

- VMEncryption/main/SupportedOS.json
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/rhel_72/encryptstates/PrereqState.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PrereqState.py
Add CentOS 7.7 and RHEL 7.7 support to ADE single pass extension
> ADE SP - add CentOS 7.7 and RHEL 7.7

- VMEncryption/main/handle.py
Fix unsupported file system warning message in dual pass extension.  
(Brings DP into parity with existing SP warning message logic)
> ADE DP - fix unsupported file system warning for dual pass extension

- VMEncryption/main/Common.py
- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/test/test_handler_util.py
* handle case of no settings files in default parse config 
* handle case of no settings file in nonquery logic
* add unit test to simulate disable when no settings file present
* update version number
> ADE SP handle case of no settings file

- VMBackup/manifest.xml
- VMBackup/prodmanifest.xml
> Updating Extension versions

- VMBackup/manifest.xml
- VMBackup/prodmanifest.xml
Updating Extension versions to release branch
> Updating Extension versions to release branch

- VMBackup/main/fsfreezer.py
- VMBackup/manifest.xml
Fix for non-int config value SafeFreezeWaitInSeconds
> Fix for non-int config value SafeFreezeWaitInSeconds

- VMBackup/main/fsfreezer.py
- VMBackup/manifest.xml
Fix for non-int config value SafeFreezeWaitInSeconds in release branch
> Fix for non-int config value SafeFreezeWaitInSeconds in release branch

- VMEncryption/main/Common.py
- VMEncryption/main/ProcessLock.py
- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/rhel_72/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/ubuntu_1604/encryptstates/PatchBootSystemState.py
1. Reject settings if fatal exception occurs while a daemon is running.
2. Preserve waagent log from pivot root environment
> Reject settings if update is called while a daemon is running

- Diagnostic/diagnostic.py
We got a few CRIs where OMI service does not start due to a possible corruption. LAD detects that OMI is not available; it attempts to restart the service. If still a problem, the component is re-installed.
> LAD: Reinstall OMI if it is failing to start as recovery action

- Diagnostic/diagnostic.py
> properly initialize var

- RDMAUpdate/main/Utils/HandlerUtil.py
- Utils/HandlerUtil.py
Fixed a typo in RDMAUpdate/main/Utils/HandlerUtil.py and Utils/HandlerUtil.py
> Fixed typo in HandlerUtil.py

- OmsAgent/Mooncake/HandlerManifest.json
- OmsAgent/Mooncake/omsagent_mc.py
- OmsAgent/Mooncake/watcherutil.py
Syncing the Mooncake omsagent code with the latest 1.12.15 code base
> Syncing MC with 1.12.15

- AzureMonitorAgent/agent.py
Added checks for existing values of the variables and replace them with new values instead of appending at the end.
> Fixed MCS env var update in /etc/default/mdsd 

- OmsAgent/HandlerManifest.json
- OmsAgent/manifest.xml
- OmsAgent/omsagent.py
- OmsAgent/watcherutil.py
- also version changes for 1.12.25
> fix octal number and ascii encoding install issues

- Diagnostic/mdsd/mdscommands/EventHubUploader.cc
> Remove the usleep call from EventHubUploader

- Diagnostic/diagnostic.py
Fix the error message as described in issue https://github.com/Azure/azure-linux-extensions/issues/948
> Fix for  issue #948

- VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/SplitRootPartitionState.py
Fixes an issue in SplitRootPartitionState that was not properly unmounting oldroot prior to advancing to next state, breaking cryptsetup commands for OS disk encryption when device was still in use.
> ADE DP fix U14 unmount oldroot sequence in SplitRootPartitionState

- VMBackup/main/PluginHost.py
- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/WaagentLib.py
- VMBackup/main/handle.sh
- VMBackup/main/patch/NSBSDPatching.py
- VMBackup/main/patch/__init__.py
This patch adds support for NSBSD OS for the Backup extension.
I installed manually the patched extension and backups now end with success.
Issue #896
> NSBSD os support for VMBackup extension

- VMEncryption/setup.py
Adding version.txt to the ZIP file since it is needed in Common.py at runtime.
> ADE SinglePass version fix

- VMEncryption/main/DiskUtil.py
- VMEncryption/main/handle.py
- VMEncryption/test/test_disk_util.py
- VMEncryption/test/test_encryption_settings_util.py
Fixing a bug found in daily test automation recentlty
> Make Single Pass Disable a little more resilient

- AzureMonitorAgent/HandlerManifest.json
- AzureMonitorAgent/agent.py
- AzureMonitorAgent/manifest.xml
- default mode is MCS if protected settings aren't provided
> AMA release 0.9.001

- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/main/oscrypto/ubuntu_1604/encryptstates/SplitRootPartitionState.py
1. Run partprobe only on root device
2. Output exit message before exiting
> ADE test failure fixes

- VMBackup/HandlerManifest.json
- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/backuplogger.py
- VMBackup/main/freezesnapshotter.py
- VMBackup/main/fsfreezer.py
- VMBackup/main/guestsnapshotter.py
- VMBackup/main/handle.py
- VMBackup/main/handle.sh
- VMBackup/manifest.xml
- VMBackup/prodmanifest.xml
Created because previous one showed removed files
> Linux Bug fixes: Calling Handle.py only when command is enable, Having default values when settings are read from vmbackup.conf 

- VMEncryption/ReleaseNotes.txt
- VMEncryption/main/Common.py
Adds release notes and increments version
> ADE DP 0.1.0.999345

- VMEncryption/ReleaseNotes.txt
- VMEncryption/main/Common.py
Add release notes and increment version
> ADE DP Release 0.1.0.999345

- Diagnostic/Utils/omsagent_util.py
Removing this hack, and Handling is directly in configure_syslog.sh
check PR https://github.com/microsoft/OMS-Agent-for-Linux/pull/1191
> remove sles11 hack, was fixed in configure_syslog.sh

- Utils/constants.py
- Utils/distroutils.py
- Utils/extensionutils.py
- VMAccess/manifest.xml
- VMAccess/vmaccess.py
> Added compatibility for python 2.6 subprocess.check_output

- OmsAgent/omsagent.py
- As discussed on email, this subprocess monkey patch is a workaround for the issue where using python-future (who made an incomplete backport of 2.7+ changes to subprocess) causes the monkey-patch used by waagent to be overridden, yielding stack traces like the following. 
```
2020/05/10 15:10:59 ERROR:Install failed with error: 'CalledProcessError' object has no attribute 'output'
2020/05/10 15:10:59 ERROR:Stacktrace: Traceback (most recent call last):
2020/05/10 15:10:59 ERROR:  File "./omsagent.py", line 264, in main
2020/05/10 15:10:59 ERROR:    exit_code, output = operations[operation]()
2020/05/10 15:10:59 ERROR:  File "./omsagent.py", line 441, in install
2020/05/10 15:10:59 ERROR:    final_check = final_check_if_dpkg_locked)
2020/05/10 15:10:59 ERROR:  File "./omsagent.py", line …
```
> OMS Double Monkey Patch

- Diagnostic/README.md
Changing default location of supported Linux distributions from Github page to Microsoft Docs page.
> Remove Supported Linux Distributions

- OmsAgent/HandlerManifest.json
- OmsAgent/omsagent.py
Reverting the original commit - 1008676020a4e5c3f8b9524b19299cc656193e58 https://github.com/Azure/azure-linux-extensions/pull/1029
> Reverting Multiple WS onboarding check

- VMEncryption/main/DiskUtil.py
- VMEncryption/main/SupportedOS.json
- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/rhel_72/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/rhel_72/encryptstates/PrereqState.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PrereqState.py
- VMEncryption/test/test_disk_util.py
- VMEncryption/test/test_utils.py
Attempt create directory only if it doesn't exist
Attempt mount an encrypted disk only if it is not already mounted
Handle redo last status if status file doesn't exist
> RHEL 7.8 support and QoS Fixes

- Utils/distroutils.py
- VMAccess/manifest.xml
Fixed ssh service name for Centos. Fix for issue https://github.com/Azure/azure-linux-extensions/issues/1157
> Fixed ssh service name for Centos

- VMEncryption/main/DiskUtil.py
- VMEncryption/main/EncryptionSettingsUtil.py
- VMEncryption/main/SupportedOS.json
- VMEncryption/main/Utils/HandlerUtil.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PrereqState.py
- VMEncryption/test/test_disk_util.py
- VMEncryption/test/test_utils.py
Try clearing encryption settings from disk during disable encryption
Attempt create directory only if it doesn't exist
Attempt mount an encrypted disk only if it is not already mounted
Handle redo last status if status file doesn't exist
> RHEL 7.8 support and QoS Fixes[DualPass]

- OmsAgent/packaging.sh
Adapt input argument since we need to package the .sha256sum and .asc now as well
> Improve Packaging Script

- AzureMonitorAgent/.gitignore
- AzureMonitorAgent/HandlerManifest.json
- AzureMonitorAgent/agent.version
- AzureMonitorAgent/apply_version.sh
- AzureMonitorAgent/manifest.xml
- AzureMonitorAgent/packaging.sh
- AzureMonitorAgent/update_version.sh
- OmsAgent/.gitignore
I have spoken with Sidd and we going to make AMA version = MDSD version
> Automate AMA extension packaging

- OmsAgent/omsagent.py
Tested on local VM, Public, MC
IMDS docs [here](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service#sample-4-getting-azure-environment-where-the-vm-is-running).
> OMS Detect Cloud with IMDS azEnvironment

- VMEncryption/main/Common.py
- VMEncryption/main/EncryptionSettingsUtil.py
Initial PR review from private branch - https://github.com/Azure/azure-linux-extensions/pull/1207
> WireServerEndpoint changes

- AzureMonitorAgent/agent.py
- LAD-AMA-Common/metrics_ext_utils/metrics_common_utils.py
- LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
- LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py
Adding extension support for AMA on Arc. Will be running a separate arc daemon to keep track of the valid key/token files for making the MSI call to Arc's hybrid service. 
**Work remaining -** Adding retry logic for arc watcher and making it more resilient.
> Adding support for AMA on Arc

- Diagnostic/lad_config_all.py
Short change for moving sinks config to public settings instead of protected
> switching sinks to public config

- OmsAgent/omsagent.py
Oracle 8 support works without any changes to the code.
> Add support for Oracle 8

- LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py
Changing virtualmachinename tag to VMInstanceId and adding deployment id only if is_lad is true
> VM Instance ID changes

- Diagnostic/ChangeLogs
- Diagnostic/mdsd/mdsd/XJsonBlobRequest.cc
- Diagnostic/mdsd/mdsd/XJsonBlobSink.hh
Fix issue #1262 
Update Changelog for LAD 3.0.131
> Fix crashing issue in XJsonBlob

- VMEncryption/main/CommonParameters.py
- VMEncryption/main/common_parameters.json
- VMEncryption/main/oscrypto/91adeOnline/crypt-run-generator-ade.sh
- VMEncryption/main/oscrypto/OSEncryptionState.py
Fix regressions for centos 7.8 image
> Fix /proc/mounts parsing and add umounts to initramfs script

- LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
ME requires auth token resource to be - https://ingestion.monitor.azure.com/
> Changing the resource for MSI auth call for ME

- VMEncryption/main/Common.py
- VMEncryption/main/EncryptionSettingsUtil.py
- VMEncryption/main/handle.py
- VMEncryption/test/test_encryption_settings_util.py
- VMEncryption/test/test_handle_migration.py
SSIRP port to dual pass.
Few migration related changes.
> Port SSIRP changes to dual pass.

- LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py
1) Added logic for generating config for the new telegraf aggregator plugin for ME (mdmratemetrics)
2) Fixed a bug where sourcing frequency was being set to 1 second for all VMI rate counters
> Adding Rate counters for VMI MDM metrics

- VMEncryption/main/ResourceDiskUtil.py
- VMEncryption/main/test/test_UbuntuPatching.py
- VMEncryption/main/test/test_check_util.py
- VMEncryption/main/test/test_handler_util.py
- VMEncryption/main/test/test_resource_disk_util.py
- VMEncryption/setup.py
- fix packaging for hook and boot scripts
- unmount /mnt from lxd namespace
> ADE SP DEV U20 fixes

- VMEncryption/main/DiskUtil.py
- VMEncryption/main/ResourceDiskUtil.py
- VMEncryption/main/TransactionalCopyTask.py
- VMEncryption/main/test/test_UbuntuPatching.py
- VMEncryption/main/test/test_check_util.py
- VMEncryption/main/test/test_handler_util.py
- VMEncryption/main/test/test_resource_disk_util.py
- VMEncryption/setup.py
- release lxd snap prior to encrypting resource disk
- update / fix unit tests for U20 resource disk scenario 
- force size params in resize to int for python3 compat
> ADE SP DEV U20 - test fixes

- VMEncryption/main/Common.py
- VMEncryption/main/DiskUtil.py
- VMEncryption/main/ResourceDiskUtil.py
- VMEncryption/main/TransactionalCopyTask.py
- VMEncryption/main/handle.py
- VMEncryption/main/test/test_UbuntuPatching.py
- VMEncryption/main/test/test_check_util.py
- VMEncryption/main/test/test_disk_util.py
- VMEncryption/main/test/test_handler_util.py
- VMEncryption/main/test/test_resource_disk_util.py
- VMEncryption/setup.py
defaults to LUKS2 sizes when resizing for in place headers on systems with cryptsetup versions >= 2.1.0
> ADE SP DEV U20 - LUKS2 

- VMBackup/main/Utils/DiskUtil.py
- VMBackup/main/Utils/ResourceDiskUtil.py
- VMBackup/main/Utils/SizeCalculation.py
- VMBackup/main/blobwriter.py
- VMBackup/main/fsfreezer.py
- VMBackup/main/mounts.py
- made DiskUtil class Singleton to make sure that mount command is executed single time
- made changes in blobowriter to make GetBlobProperties only once per blob
- Optimized FSFreezer to get resource mount only once
> Optimizing Extension code

- AzureMonitorAgent/agent.py
This is to fix the rolling upgrade scenario.
> AMA: instruct the pkg manager to overwrite the conf file instead of prompting

- VMEncryption/main/oscrypto/rhel_72_lvm/RHEL72LVMEncryptionStateMachine.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PatchBootSystemState.py
merge latest from ade-singlepass-dev to ade-sp-dev-u20 test branch
> merge ade-singlepass-dev to ade-sp-dev-u20

- AzureMonitorAgent/agent.py
- fix to handle stale pids (whem VM reboots) from arc watcher thread
> fix to handle stale pids (whem VM reboots) from arc watcher thread

- AzureMonitorAgent/agent.py
Pass managed identity settings to mdsd. Settings are passed via extension public settings:
```json
"setings":
{
"authentication":
{
"managedIdentity":
{
"identifier-type": "{object_id, client_id, mi_res_id}",
"identifier-value": "<guid OR resource id>"
}
}
}
```
> AMA Managed Identity

- VMEncryption/main/handle.py
replace file() with open() for p3 compat
> ade spd p23str

- AzureMonitorAgent/agent.py
- LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
Originally needed for private links. Though I moved endpoint logic to mdsd, we may need the IMDS code in the future so I left it here along with a small fix for metrics.
> AMA IMDS helpers

- AzureMonitorAgent/agent.py
- LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
Error discovered when testing FF/MC deployment. Also did some cleanup of whitespace/spelling nits.
> Detect ARM domain based on Azure Environment

- VMEncryption/main/CryptMountConfigUtil.py
- VMEncryption/main/handle.py
- fix data disk disable after enable on p3
> EJ ADE SPD fix to enable/disable flow

- OmsAgent/omsagent.py
> Fix perms to /var/log/azure and support for AW2

- AzureMonitorAgent/agent.py
Have seen cases where `MDSD_OPTIONS` was defined before `MDSD_LOG` which meant that mdsd was trying to log in `/`. Also fixed trailing whitespace/tabs.
> Fix defaults file ordering

- AzureMonitorAgent/agent.py
If disk is full, our disk checks will also cause uninstall/disable to short circuit and fail; lets be resilient to that.
Also, remove usage of internal "oneagent".
> Fix for blocked uninstall due to disk

- VMBackup/main/HttpUtil.py
- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/backuplogger.py
- VMBackup/main/common.py
- VMBackup/main/guestsnapshotter.py
- VMBackup/main/handle.sh
https://msazure.visualstudio.com/One/_workitems/edit/10503507
https://msazure.visualstudio.com/One/_workitems/edit/9293711
> Logging in utc and writing status to temp file before renaming it

- VMEncryption/main/BekUtil.py
- VMEncryption/main/CommandExecutor.py
- VMEncryption/main/check_util.py
- VMEncryption/main/handle.py
- VMEncryption/main/test/test_check_util.py
Fix regex for resource group name and format_exc for py3
> Fix Key Vault resource ID check.

- AzureMonitorAgent/agent.py
- AzureMonitorAgent/agent.version
- AzureMonitorAgent/packaging.sh
- LAD-AMA-Common/metrics_ext_utils/metrics_constants.py
- LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
Switch from azure-mdsd => azuremonitoragent package
> Switch to azuremonitoragent package

- AzureMonitorAgent/agent.py
- LAD-AMA-Common/metrics_ext_utils/metrics_common_utils.py
[Based on systemd docs](https://www.freedesktop.org/software/systemd/man/sd_booted.html).
> Fix check for systemd

- DSC/dsc.py
Changes to remove the OMI port dependency.
> Removing OMI port dependency

- AzureMonitorAgent/agent.py
> support rhel

- AzureMonitorAgent/agent.py
Update agent.py to reflect [officially supported distros](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/agents-overview#linux).
> [AMA] Correct distro support list

- VMEncryption/main/Common.py
- VMEncryption/main/CryptMountConfigUtil.py
- VMEncryption/main/EncryptionMarkConfig.py
- VMEncryption/main/OnlineEncryptionHandler.py
- VMEncryption/main/OnlineEncryptionResumer.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/rhel_81/encryptstates/PatchBootSystemState.py
1. Setup encryption layer on all disk before starting the background encryption.
2. Return success after the encryption layer is set and VM has rebooted for OS encryption.
3. Reboot resilience for background encryption phase
> Setup encryption layer for all disks and do encryption in background.

- VMEncryption/main/Common.py
- VMEncryption/main/CryptMountConfigUtil.py
- VMEncryption/main/DiskUtil.py
- VMEncryption/main/EncryptionEnvironment.py
- VMEncryption/main/EncryptionMarkConfig.py
- VMEncryption/main/OnlineEncryptionHandler.py
- VMEncryption/main/OnlineEncryptionResumer.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/rhel_81/encryptstates/PatchBootSystemState.py
Bring online encryption to dev branch.
> Enhance Online Encryption support.

- AzureMonitorAgent/agent.py
Start amacoreagent in config port mode for GCS scenarios
> Start amacoreagent when azuremonitoragentmgr service is enabled

- OmsAgent/omsagent.py
The sequence number check was intended to determine if there was a config change from previous install/upgrade and whether enable () should be skipped because it is  called  after VM restart. However, this check only works when upgrade happens with minor version change and not with patch versions. Patch version falls into no config change path and in result agent onboarding is being skipped after upgrade .
> Move sequence number check to be for service restart only to fix patch version upgrade scenarios when agent onboarding is being skipped

- VMEncryption/main/DiskUtil.py
- VMEncryption/main/SupportedOS.json
- VMEncryption/main/check_util.py
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/rhel_81/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/rhel_81/encryptstates/PrereqState.py
- VMEncryption/main/patch/AbstractPatching.py
- VMEncryption/main/patch/oraclePatching.py
- VMEncryption/main/patch/redhatPatching.py
- VMEncryption/main/test/test_UbuntuPatching.py
- VMEncryption/main/test/test_check_util.py
- VMEncryption/main/test/test_oraclePatching.py
- VMEncryption/main/test/test_redhatPatching.py
- VMEncryption/main/test/test_utils.py
1. Add support for Oracle 8.5
2. Auto support minor version upgrade for redhat 8 and Oracle 8
> Add support for Oracle.

- VMEncryption/main/handle.py
Fix the bug that does not call resume encryption for new data disks.
> Fix resume encryption for new data disks.

- AzureMonitorAgent/agent.py
Got ahead of myself and added this to agent.py expecting support in next release. Looks like we're still blocked on ME binary
> Revert adding arm64 CentOS7

- AzureMonitorAgent/agent.py
Add arm64 centos 7 support along with centos7 specific ME binary changes
> arm64 centos 7 support

- VMEncryption/main/ResourceDiskUtil.py
- VMEncryption/main/handle.py
- VMEncryption/main/patch/UbuntuPatching.py
- VMEncryption/main/test/test_UbuntuPatching.py
- VMEncryption/main/test/test_resource_disk_util.py
- Generate passphrase in case of resource disk only encryption when recovering from service heal or reallocation
> Improve RD Only logic

- AzureMonitorAgent/agent.py
Tested for heartbeat, syslogs and perf data using marketplace image for arm64 mariner 2
> Add arm64 mariner 2 support

- LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py
> Increment udp_payload size from 1KB to 2KB for influxdb output.

- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/Utils/HostSnapshotObjects.py
- VMBackup/main/Utils/Status.py
- VMBackup/main/common.py
- VMBackup/main/freezesnapshotter.py
- VMBackup/main/guestsnapshotter.py
- VMBackup/main/hostsnapshotter.py
1. Changes in two classes to support two new parameters. The class that processes the Host Response (HostSnapshotObjects.py) and the class that returns response to CRP (status.py).
2. Their corresponding processing functions _get_snapshot_info_() and _update_snapshotinfoarray_() are updated.
3. When a DirectDrive disk is included, the snapshot mode is set to Host only. 
Design doc for the changes available [here](https://microsoft.sharepoint.com/:w:/t/AzureBackupTeam/Ed7HBzHa9Z9GpSnhIEwLrSIBS-Zsv2fL4_y_V3vA6U0AeQ?wdOrigin=TEAMS-ELECTRON.p2p.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1655202817225).
> DirectDrive disk support for backup extensions

- VMEncryption/main/SupportedOS.json
- VMEncryption/main/Utils/waagent
- VMEncryption/main/oscrypto/OSEncryptionState.py
- VMEncryption/main/oscrypto/rhel_81/encryptstates/PatchBootSystemState.py
- VMEncryption/main/patch/AbstractPatching.py
- VMEncryption/main/patch/__init__.py
- VMEncryption/main/patch/marinerPatching.py
- VMEncryption/main/patch/redhatPatching.py
Initial changes for Mariner ADE support into staging branch for testing.
> Initial Mariner ADE Support

- Diagnostic/HandlerManifest.json
- Diagnostic/diagnostic.py
- Diagnostic/shim.sh
> [LAD 4.0] Add shim

- Diagnostic/HandlerManifest.json
- Diagnostic/diagnostic.py
- Diagnostic/shim.sh
> [LAD 3.0] Add shim

- VMEncryption/main/SupportedOS.json
- VMEncryption/main/Utils/waagent
- VMEncryption/main/handle.py
- VMEncryption/main/oscrypto/OSEncryptionState.py
- VMEncryption/main/oscrypto/rhel_72/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/rhel_81/encryptstates/PatchBootSystemState.py
- VMEncryption/main/oscrypto/rhel_81/encryptstates/PrereqState.py
- VMEncryption/main/patch/AbstractPatching.py
- VMEncryption/main/patch/__init__.py
- VMEncryption/main/patch/centosPatching.py
- VMEncryption/main/patch/marinerPatching.py
- VMEncryption/main/patch/redhatPatching.py
1. Add support for Mariner (Author: Max)
2. Improve boot UUID detection logic
3. Onboard CentOS to online encryption
> Ade mainer sup

- VMBackup/main/HttpUtil.py
- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/handle.py
Removed the typos and differentiated between various commandToExecute and starting daemon
> FixedTheTyposAndCreatedMoreClearLogs

- VMAccess/manifest.xml
Update manifext.xml version to 1.5.13 for VMAccess
> Update manifext.xml for VMAccess

- AzureMonitorAgent/agent.py
> AMA Install flag for FIPS RPM

- AzureMonitorAgent/agent.py
Reverts Azure/azure-linux-extensions#1611
> Revert "AMA Install flag for FIPS RPM"

- AzureMonitorAgent/agent.py
Changes in the PR:
1. Removed magic number 52.
2. Added errors from package manager corrupt  paths to be excluded from SLA
3. Removed stderr logging for each command line execution based on guest agent guidance on how this stream is used,. Should help with improving overall time execution of agent.py as path was being called for every command in each extension operation.
> AMA extension error handling and error reporting improvements

- AzureMonitorAgent/agent.py
> Don't change permissions on defaults file as it breaks rpm verification

- AzureMonitorAgent/agent.py
Add traceFlags settings to enable mdsd tracing in AMA via public settings.
> Add traceFlags settings to enable mdsd tracing in AMA via public settings

- AzureMonitorAgent/agent.py
- AzureMonitorAgent/ama_tst/modules/install/check_os.py
Adding support for RHEL 9 in AMA.
> Add RHEL9 Support

- VMEncryption/main/HttpUtil.py
- VMEncryption/main/IMDSUtil.py
- VMEncryption/main/check_util.py
- VMEncryption/main/handle.py
1. IMDS call must be a no proxy call. IMDS recommendation.
2. IMDS failure as non-terminal failure.
> using no proxy and IMDS failure as non terminal.

- VMEncryption/main/patch/marinerPatching.py
Use grubby to add kernel parameters for Mariner 2.0
For preview, grub.cfg was manually modified which is not a recommended.
Using grubby will resolve it and make ADE ready for official support of Mariner 2.0
The PR will be merged after Mariner image is updated to include grubby package.
> Add official support for Mariner 2.0.

- VMEncryption/volume-notif-svc/UdevVolNotif.c
- VMEncryption/volume-notif-svc/azure-diskencryption-vol-notif.service
- VMEncryption/volume-notif-svc/daemon_delay.sh
adding ADE running into VNS service. 
The below files must be placed in /var/lib/waagent/Microsoft.Azure.Security.Edp.AzureDiskEncryptionForLinuxTest1-1.3.x.x in build. 
volume-notif-svc\daemon_delay.sh
volume-notif-svc/azure-diskencryption-vol-notif.service
ade-volume-notif-svc
> integrating ADE in VNS service

- VMBackup/main/handle.py
Updated handle.py to log error when creating daemon process
> Updated handle.py to log error when creating daemon process

- Diagnostic/HandlerManifest.json
- Diagnostic/diagnostic.py
- Diagnostic/manifest.xml
- Diagnostic/shim.sh
Lad 4.0 release main branch: https://github.com/Azure/azure-linux-extensions/tree/release/lad4.0
Last LAD 4 release 4.1.10 tag: https://github.com/Azure/azure-linux-extensions/releases/tag/lad-4.1.10
LAd 4.1.10 release branch codebase: https://github.com/Azure/azure-linux-extensions/tree/narinem-lad-4.1.10
>  Merge LAd 4.1.10 release branch into master to baseline master

- AzureMonitorAgent/agent.py
per https://msazure.visualstudio.com/One/_wiki/wikis/One.wiki/233012/VM-Extension-Authoring-for-Arc?anchor=4.-proxy-support
> Support Arc-Enabled Servers proxy configuration file

- VMEncryption/main/BekUtilVolumeImpl.py
- VMEncryption/main/Common.py
- VMEncryption/main/CryptMountConfigUtil.py
- VMEncryption/main/DiskUtil.py
- VMEncryption/main/EncryptionEnvironment.py
- VMEncryption/main/IMDSUtil.py
- VMEncryption/main/OnlineEncryptionHandler.py
- VMEncryption/main/OnlineEncryptionResumer.py
- VMEncryption/main/TransactionalCopyTask.py
- VMEncryption/main/VolumeNotificationService.py
- VMEncryption/main/check_util.py
- VMEncryption/main/handle.py
- VMEncryption/main/patch/AbstractPatching.py
- VMEncryption/main/patch/UbuntuPatching.py
- VMEncryption/main/test/test_bek_util.py
- VMEncryption/main/test/test_check_util.py
- VMEncryption/setup.py
- VMEncryption/volume-notif-svc/UdevVolNotif.c
- VMEncryption/volume-notif-svc/ade_daemon_delay.sh
- VMEncryption/volume-notif-svc/azure-diskencryption-vol-notif.service
- VMEncryption/volume-notif-svc/build.sh
1. data disk encryption
2. Volume notification service driver code.
3. placing VNS driving logic in ADE.
> data disk encryption

- VMBackup/main/Utils/DiskUtil.py
- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/backuplogger.py
- VMBackup/main/blobwriter.py
- VMBackup/main/handle.py
[PR #1698](https://github.com/Azure/azure-linux-extensions/pull/1698/files) was created to add more logs that can help debug issues better. however, the new logs seem to be causing issues like overwhelming the log file size, status update issues. Reverting those changes.
> Reverting PR #1698 to remove additional logging

- AzureMonitorAgent/ama_tst/modules/install/check_ama.py
ICM : 413679459 reported for python 3.6
> update ama troubleshooter to work with python3

- AzureMonitorAgent/agent.py
since it is available only from Python 3.3
> Replace shutil.which

- AzureMonitorAgent/agent.py
This reverts commit 4646db4a48ca15210cd0978a54f26a38ca1747cd.
> Revert "In GCS scenarios, ensure that AMACoreAgent is running (#1788)"

- VMEncryption/main/handle.py
code to fix the regression test cases.
> do not umount /mnt for reimage scenario for encryptformatall

- AzureMonitorAgent/agent.py
This reverts commit 065757b47b69f4116e376c10f66693f8f483b0f5.
> In GCS scenarios, ensure that AMACoreAgent is running

- AzureMonitorAgent/agent.py
Revert "Delete the PA.json file when AMA is configured for 1P mode (#1805)"
This reverts commit 7b32a61cb24e236afd5947c67b95d9172046552b.
> Revert "Delete the PA.json file when AMA is configured for 1P mode (#1805)"

- VMEncryption/main/check_util.py
- VMEncryption/main/test/test_check_util.py
Updating the resourceId for ManagedHSM
> Update resid for managedHSM

- AzureMonitorAgent/agent.py
- OmsAgent/omsagent.py
Fix for the issue: https://github.com/Azure/azure-linux-extensions/issues/1848
> do not reset /var/log/azure folder permissions with AMA and OMS extension install.

- OmsAgent/omsagent.py
OS parsing was slightly out of date, relying on functions that were deprecated in later Python versions, as well as breaking on some local builds of Python. These changes mimic the ones made in AMA a while back.
AMA PR: #1249 
AMA code reference: [azure-linux-extensions/AzureMonitorAgent/agent.py](https://github.com/Azure/azure-linux-extensions/blob/e8335c900f37ef11da950a923b09fd370c26bdf5/AzureMonitorAgent/agent.py#L1520)
> Update OS Distro/Version Parsing

- AzureMonitorAgent/agent.py
Add "mariner" as a supported distro when parsing "mariner 1.0
> Update AMA Supported OS

- AzureMonitorAgent/HandlerManifest.json
set based on benchmarks and real-world guest agent telemetry
> Add cpu quotas for AMA

- AzureMonitorAgent/agent.py
- AzureMonitorAgent/packaging.sh
- AzureMonitorAgent/services/metrics-extension.service
- LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py
to handle occasional bursts in traffic that ME isn't able to handle
https://portal.microsofticm.com/imp/v3/incidents/incident/463024897/summary
> Change from UDP to Unix Socket for telegraf => ME communication

- AzureMonitorAgent/agent.py
- AzureMonitorAgent/ama_tst/modules/connect/connect.py
- AzureMonitorAgent/ama_tst/modules/general_health/check_status.py
Disable systemd checks for azuremonitor-coreagent and azuremonitor-agentlauncher on aarch64
> Disable systemd checks for azuremonitor-coreagent and azuremonitor-agentlauncher on aarch64

- AzureMonitorAgent/agent.py
- AzureMonitorAgent/packaging.sh
Install and run KqlExtension proc only in 3P mode and non aarch64 platforms.
> enable kql extension install

- AzureMonitorAgent/agent.py
based on https://dev.azure.com/msazure/One/_workitems/edit/27823717/
> Fix AMA extension install/enable failures

- VMAccess/manifest.xml
upversion vmaccess linux for publishing signature.
> upversion vmaccess linux

- AzureMonitorAgent/agent.py
fix for https://portal.microsofticm.com/imp/v5/incidents/details/536301475/summary
> Handle non-ascii output from running commands in python wrapper

- AzureMonitorAgent/agent.py
based on https://portal.microsofticm.com/imp/v5/incidents/details/551879113/summary
> Ensure python extension code doesn't use proxy for IMDS

- VMBackup/main/Utils/HandlerUtil.py
- VMBackup/main/Utils/LogHelper.py
The current code would not work with python <2.7 versions due to print statements in clearOldFilesInDirectory logic. Fixed it.
> Add Compatibility for older python versions

- AzureMonitorAgent/agent.py
Fix for https://portal.microsofticm.com/imp/v5/incidents/details/578913013/summary
> Fix for persistent fluent-bit config update without any port change

- AzureMonitorAgent/agent.py
- LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
* use appropriate fx and eat exceptions
* move arca to mcs path only
> [release/1.33] use appropriate fx and eat exceptions (#2012)

- AzureMonitorAgent/agent.py
based on https://portal.microsofticm.com/imp/v5/incidents/details/593461150/summary
> Prevent semanage spam in Oracle/RH while checking for port config

- AzureMonitorAgent/agent.py
prevent parsing issue on python3 < 3.6 and improve logging around imds
> improve imds response handling

- VMBackup/main/hostsnapshotter.py
For some customer VMs with DD disks, the processing of the BHS response in get_snapshot_info(responseBody) takes a long time. In certain cases, this delay exceeds 60 seconds, causing the thaw signal to be triggered late (after 60 seconds).
Since this logic is only responsible for post-processing the BHS response and does not need to be within the critical freeze section, similar to the windows extension logic moved this out to prevent unnecessary delays in the freeze/thaw workflow.
> Moved BHS Response Processing Outside Critical Freeze Section

- AzureMonitorAgent/agent.py
- LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
> More E0606 pylint error fixes

- AzureMonitorAgent/agent.py
For e.g.,
"patch.mode": "",
"proxy.bypass": [
"AMA",
"Arc"
],
"proxy.url": "http://foo.com:3131",
> Arc proxy.bypass is an array

- AzureMonitorAgent/agent.py
Fix an issue where AMA install can fail if a previous attempt was interrupted
> Fix an issue where AMA install can fail if a previous attempt was interrupted

- AzureMonitorAgent/agent.py
- AzureMonitorAgent/packaging.sh
- AzureMonitorAgent/services/metrics-extension-cmv2.service
- LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
Adding azureotelcollector to run conditionally on certain regions
> Patch for 1.35

- AzureMonitorAgent/agent.py
Init variables in `agent.py` to pass Linter
> Linter fixes in agent.py

- AzureMonitorAgent/agent.py
- AzureMonitorAgent/apply_version.sh
- LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
* Enable metrics-extension service always
* Fix missing agent version in metrics-extension-cmv2.service
> Sajithmuh patch 1.35

- Utils/handlerutil2.py
- VMAccess/errorclarification.py
- VMAccess/errrorclarification.py
- VMAccess/vmaccess.py
Adding error clarification for vmaccess extension.
> T feadeaga user error

- AzureMonitorAgent/ama_tst/modules/main.py
- AzureMonitorAgent/ama_tst/modules/metrics_troubleshooter/__init__.py
- AzureMonitorAgent/ama_tst/modules/metrics_troubleshooter/metrics_troubleshooter.py
- AzureMonitorAgent/packaging.sh
Extending `ama_troubleshooter.sh` to collect useful information to troubleshoot metrics-extension service.
> Add Metrics Troubleshooter

- AzureMonitorAgent/agent.py
Remove non-zero exit code to proceed with install.
> Agent.py fixes for Install() and Uninstall()

- Utils/distroutils.py
Reverts Azure/azure-linux-extensions#2083
> Revert "Adding crypt_r support for python 3.13 (Ubuntu 25.04, distros with ro…"
