Azure/azure-linux-extensions

AzureEnhancedMonitor/README.md, AzureEnhancedMonitor/ext/aem.py, AzureEnhancedMonitor/ext/test/test_aem.py, AzureEnhancedMonitor/nodejs/setaem.js
1.	Switch to LinuxDiagnostic extension version 2.0
-Switched.
2.	Add support for table endpoint, pass table endpoint to LinuxDiagnostic extension as param.
-Updated the node js script.
a.	Add/modify perf counters, for details, see the email thread bellow
-Extension status has been displayed on Azure Portal. And It is checked by Handler, if just check it in PrefCounters, you can't judge whether it is dead status or not. So I don't think it should be write in PrefCounters.
b.	Add an perf counter(\config\errors) for error code
-Added. By record the latest error in disk.
c.	\network({0})\Network Read Bytes and \network({0})\Network Write Bytes are reported per NIC instance. Network adapter must be of Ethernet type, other NICs are filtered out.
Before the counters were cumulative values (sum) …
=> AzureEnhancedMonitor V2

CustomScript/HandlerManifest.json, CustomScript/customscript.py
Users can put commandToExecute in the protected settings if they want pass their sensitive data, for e.g. password.
If commandToExecute is specified both in public and protected settings, the extension will fail with an error.
=> Support passing sensitive data

CustomScript/HandlerManifest.json, CustomScript/customscript.py, docs/handler-registration.md
1. Move downloading scripts and internal DNS check into the daemon process
2. Provide an option to disable internal DNS check
3. Add a timeout to urllib2.urlopen()
=> [CustomScript] Avoid the 5 minutes timeout

OSPatching/patch/UbuntuPatching.py
Add --force-confdef when installing packages (to prevent freezing at confirmation prompt)
Add automated execution of --configure --force-confdef if package install fails
=> Gracefully handle user-modified config files

Utils/HandlerUtil.py
Diagnostics has their own copy of Utils, and this is the copy used by CustomScript.
=> Atomically write the status file.

VMEncryption/main/OnGoingItemConfig.py
Fixes the crash:
> 2016/04/10 23:31:36 [Microsoft.OSTCExtensions.AzureDiskEncryptionForLinux-1.0]2351: Error Failed to enable the extension with error: global name 'current_slice_index' is not defined, stack trace: Traceback (most recent call last):
> 2016/04/10 23:31:36   File "./main/handle.py", line 734, in daemon
> 2016/04/10 23:31:36     ongoing_item_config.load_value_from_file()
> 2016/04/10 23:31:36   File "/var/lib/waagent/Microsoft.OSTCExtensions.AzureDiskEncryptionForLinux-0.1.0.999104/main/OnGoingItemConfig.py", line 132, in load_value_from_file
> 2016/04/10 23:31:36     self.current_slice_index = self.get_current_slice_index()
> 2016/04/10 23:31:36   File "/var/lib/waagent/Microsoft.OSTCExtensions.AzureDiskEncryptionForLinux-0.1.0.999104/main/OnGoingItemConfig.py", line 90, in …
=> current_slice_index is undefined, use current_slice_index_value

Diagnostic/diagnostic.py, Diagnostic/license.txt
mdsd is now built as statically as possible, allowing us not to distinguish distros/versions. So update diagnostic.py's mdsd install code for this change.
=> [LAD] Prepare for unified static mdsd build

Diagnostic/Utils/HandlerUtil.py, Diagnostic/diagnostic.py
- Remove unused XML attribute to avoid unnecessary mdsd warning
- Remove unnecessary dependency installation
- Report proper extension version in logs (addressing Issue #140)
@LiweiPeng : Please review this for Issue #140 and other issues you raised (the mdsd warning).
@ahmetalpbalkan : This applies to LAD only (because LAD's Utils directory is forked before we took over), so this change doesn't directly address #143, but I suppose a similar approach could be applied there. Note that each extension's HandlerUtility instantiation calls will need to be updated, which I suppose we should be very careful about... Also I still don't like the fact that the extension's version is hard-coded in the script, but I couldn't find the version string from anywhere else. Let me know if you know about …
=> [LAD] Misc updates for 2.3.9001

CustomScript/customscript.py
I needed the ability to disable the internal DNS check, and while the public_setting is exposed, there is a bug where it was not being handled correctly and didn't work.  Setting a var to a string value makes it a 'true' boolean value when used for a boolean operation regardless of what the string value actually is.
This change uses the strtobool function to convert the string value that is optionally defined in public_settings ('enableInternalDNSCheck') into a true boolean value for the 'enable_idns_check' variable, so that the idns check is executes as expected.  Omitting 'enableInternalDNSCheck' from the public_settings results in a default of 'true' (as it was) while allowing a string value of 'y, yes, t, true, on or 1' for boolean true and a string value of 'n, no, f, false, off and …
=> Fix for Internal DNS Check

CustomScript/.gitignore, Makefile
Use the version and type (name) from an extension's manifest.xml to
create an extension's zip archive.
Support building with directories that contain whitespace.
=> Simple Makefile to build extensions.

RDMAUpdate/main/patch/centosPatching.py, VMBackup/main/patch/centosPatching.py, VMEncryption/main/handle.py, VMEncryption/main/patch/centosPatching.py
Attempting to use Azure Recovery Services Vault with our OpenLogic-based CentOS 6.8 VMs (updated from the 6.7 marketplace images), we traced a failure back to the `centosPatching.py` file in the VMBackup extension. This file maps paths of specific command line utilities used by the extension, and already differentiates CentOS 6.5, 6.6, and 6.7, but since 6.8 was not included, mapped these paths on the last version incorrectly. This ultimately led to an inability to back the VM up via Azure Recovery Services Vault due to a failure to be able to interact with the necessary command line utilities. In the process of resolving this issue for VMBackup, we also noticed that RDMAUpdate and VMEncryption had similar problems, and decided to resolve those too.
=> CentOS 6.8 support in RDMAUpdate, VMBackup, and VMEncryption extensions.

Diagnostic/diagnostic.py
Fixes [issue 224](https://github.com/Azure/azure-linux-extensions/issues/224). Also fixes an insignificant-to-OMI typo that offends my sense of order and rightness in the world.
=> Write generated perfcfg query elements to only one OMI parent element.

VMAccess/CHANGELOG.md, VMAccess/README.md, VMAccess/manifest.xml, VMAccess/vmaccess.py
Plumb the expiration value through when creating a new account.  This was documented as working, but was not actually implemented per the [docs][1].
I made a few changes based on PEP recommendations.
Closes #229
[1]: https://azure.microsoft.com/en-us/blog/using-vmaccess-extension-to-reset-login-credentials-for-linux-vm/
=> vmaccess: enable expiration of accounts

Diagnostic/diagnostic.py
If running in a non-hosted environment, the HostingEnvironmentConfig.xml file will be unavailable, which means the DeploymentId is unavailable (and almost certainly irrelevant). Rather than throwing an error, just skip adding the DeploymentId as an IdentityComponent in the mdsd config (i.e. don't bother adding it as an extra column present in every table row driven by portal configuration).
=> Handle missing DeploymentId gracefully (don't add as IdentityComponent)

VMAccess/CHANGELOG.md, VMAccess/vmaccess.py
If the user specifies a password, then VMAccess must ensure password
authentication will be accepted by SSHD.  In this case, the code failed
to backup sshd_config, and failed to restart the daemon to ensure the
config change took effect.
=> vmaccess: backup sshd_config and restart SSHD

VMAccess/CHANGELOG.md, VMAccess/manifest.xml, VMAccess/vmaccess.py
Now that VMAccess accepts a empty password, and ignores it the old and
expected behavior of not passing it in the first place must still be
honored.
=> vmaccess: None check for password

CustomScript/README.md
Explicitly state that Debian 8 and higher are supported.
=> Debian 8 Support

Diagnostic/diagnostic.py, Utils/HandlerUtil.py
This change (originally from @jasonzio) is to stop using /tmp/kk while decrypting protectedSettings. Since this affects all OSTC extensions, this needs to be reviewed separately by folks other than LAD devs. @boumenot , would you please add other people who should review this change as well? I'm asking you for this, thinking you'd know more people involved with the other OSTC extensions. Thanks.
=> [Handler] Stop using /tmp/kk when decrypting protectedSettings

Utils/HandlerUtil.py
/cc @boumenot @mbearup @krkhan 
Python 2.6 doesn't support zero-length format fields, so the previous fix (stop using /tmp/kk from protectedSettings decryption code path) fails on all Python 2.6-based distro versions (mostly RedHat 6-based).
Forgot to add a link to the relevant info: [http://stackoverflow.com/questions/21034954/valueerror-zero-length-field-name-in-format-in-python2-6-6](http://stackoverflow.com/questions/21034954/valueerror-zero-length-field-name-in-format-in-python2-6-6)
=> [Handler] Fix /tmp/kk fix regression on Python 2.6

Diagnostic/ChangeLogs, Diagnostic/diagnostic.py, Diagnostic/manifest.xml
Current mdsd behavior is that its VmSize is already >2000000 even at the beginning, so the original logic won't work. Changing the unit from VmSize to VmRSS for that reason.
Also need to bump up the version number, because the faulty code is already deployed (only to 1 region, following the safe deployment practice).
=> [LAD] Update memory leak threshold for current mdsd behavior

VMEncryption/main/Common.py, VMEncryption/main/DiskUtil.py, VMEncryption/main/EncryptionMarkConfig.py, VMEncryption/main/KeyVaultUtil.py, VMEncryption/main/Utils/HandlerUtil.py, VMEncryption/main/handle.py, VMEncryption/main/oscrypto/centos_68/CentOS68EncryptionStateMachine.py, VMEncryption/main/oscrypto/centos_68/encryptstates/SplitRootPartitionState.py, VMEncryption/main/oscrypto/centos_68/encryptstates/UnmountOldrootState.py, VMEncryption/main/oscrypto/rhel_68/RHEL68EncryptionStateMachine.py, VMEncryption/main/oscrypto/rhel_68/encryptstates/UnmountOldrootState.py, VMEncryption/main/oscrypto/rhel_72/RHEL72EncryptionStateMachine.py, VMEncryption/main/oscrypto/rhel_72/encryptstates/PrereqState.py, VMEncryption/main/oscrypto/rhel_72_lvm/RHEL72LVMEncryptionStateMachine.py, VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PrereqState.py, VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/UnmountOldrootState.py, VMEncryption/main/oscrypto/ubuntu_1404/Ubuntu1404EncryptionStateMachine.py, VMEncryption/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py, VMEncryption/main/patch/centosPatching.py, VMEncryption/main/patch/redhatPatching.py
- Support OS disk encryption on CentOS 7.3
- Support OS disk encryption on RHEL 6.8
- Support OS disk encryption on CentOS 6.8
- Support LVM OS disk encryption on RHEL & CentOS 7.3
- Skip OS disk and resource disk volumes based on device serial IDs if only data disks are being encrypted. So that if customer has unsupported OS partitioning scheme, they can still use data disk encryption.
- Cleaned up redundant package depencies
- Fail decryption explicitly if OS is encrypted
- Logging improvements
- Bugfixes
=> AzureDiskEncryptionForLinux March Release

OmsAgent/Fairfax/HandlerManifest.json, OmsAgent/Fairfax/omsagent_ff.py, OmsAgent/HandlerManifest.json, OmsAgent/omsagent.py
Improve errors and add check for workspace ID and key formats
Changed bundle version in omsagent.py
Add better error messages for common error codes
Do not print out shared key with onboarding command
Explicitly allow Ubuntu 16.10 to install/enable
Corrected dpkg retry logic
Add handling for WAAgent binary version 2.0.14 RunGetOutput
(RunGetOutput added a third parameter for version 2.0.16)
@NarineM
=> OmsAgent: Implement backups for hutil and waagent methods

Diagnostic/ChangeLogs, Diagnostic/README.md, Diagnostic/Utils/LadDiagnosticUtil.py, Diagnostic/diagnostic.py, Diagnostic/lad_config_all.py, Diagnostic/manifest.xml, Diagnostic/tests/var_lib_waagent/lad_dir/config/lad_settings_metric.json
Use omsagent's sudo_tail input plug-in to read files regardless of mode (#390)
Set valid extension substatus if parsing the config raises an exception (#398)
Handle leading '?' in SAS token (#399)
Strip names when splitting sink names (#400)
Run all the unit tests as part of BVT
Small corrections to README
Fixed typos in LAD 2.3-compatible config sample (in tests/)
=> Small fixes to open issues

DSC/dsc.py, DSC/manifest.xml
Oracle by default supports python 2.6. Because of this, some of the python code is NOT working in 2.6 but in latest. @eshaparmar
=> DSCForLinux: Made fixes for Oracle distro

Diagnostic/Utils/lad_logging_config.py
The sudo_tail input plug-in requires a run_interval which controls how often it checks for new content in the file(s) it's monitoring.
=> Add run_interval to in_sudo_tail fluentd config

Makefile
Fix support on Debian 8 and greater by shipping waagent with OSTC extensions (at least most of them).
=> Ship waagent with extension

OmsAgent/Fairfax/HandlerManifest.json, OmsAgent/Fairfax/omsagent_ff.py, OmsAgent/HandlerManifest.json, OmsAgent/omsagent.py
Implemented loose list_workspaces method in detect_multiple_connections for new install case
Restart omsagent after enable and reorganize some code
Restarting will be necessary while some solutions are not multi-homing-enabled and all processes are started during install
This version of the extension will be released as 1.4.45.3, containing OMSAgent bundle version 1.4.1-45.
=> OmsAgent: Stop Install in case of stopOnMultipleConnections with SCOM connection

Diagnostic/ChangeLogs, Diagnostic/README.md, Diagnostic/Utils/lad_ext_settings.py, Diagnostic/lad_config_all.py
Fixes #451 
Also, reject any attempt to support storage key _a la_ LAD 2.3; while LAD 2.3 continues to support that for backwards compatibility, it's not a good thing from a security standpoint. With this change, if a user attempts to pass that to LAD 3.0, the extension will refuse to start up.
=> Require SAS token cred; reject storageKey cred

Diagnostic/diagnostic.py
Exceptions shouldn't leak from the configuration processing code. If they do, though, a traceback would make it easier to find the problem.
=> Report traceback when unhandled exception occurs while building configs.

Diagnostic/Utils/misc_helpers.py, Diagnostic/diagnostic.py
During -enable on non-systemd distros, diagnostic.py would start another instance of LAD in the -daemon role, checking every five seconds to see if the child started. If the child started and died during one of the 5-second sleep periods (writing a substatus in the process), the -enable parent would miss that. After a total of 20 (now futile) waiting periods, the -enable parent would overwrite the substatus written by the failed -daemon instance. This change eliminates the waiting period. Instead, the -enable instance starts the -daemon instance and immediately writes a "I've started the daemon" substatus. The -daemon instance will overwrite that with either success or failure, appropriately.
When running on systemd-enabled distros, that's exactly how LAD already behaves.
=> Fix race when starting -daemon instance. Improve error messages.

VMEncryption/main/Common.py, VMEncryption/main/oscrypto/centos_68/encryptstates/SplitRootPartitionState.py
Fix for https://icm.ad.msft.net/imp/v3/incidents/details/49002787/home
For this fix we wait for the partition table changes to be read before proceeding to format the new drives.
=> VMEncryption: Centos partition issue fix

OmsAgent/Fairfax/HandlerManifest.json, OmsAgent/Fairfax/omsagent_ff.py, OmsAgent/HandlerManifest.json, OmsAgent/omsagent.py
vmResourceId: auto-injection from azure metadata service when vmResourceId is not sent from the extension.
@NarineM
=> OMS Linux Agent Extension - vmResourceID auto-injection

OmsAgent/Fairfax/omsagent_ff.py, OmsAgent/omsagent.py
* Get vmResourceId from Metadata API if not provided in protected settings
* Retry workspace provisioning when OMS/AMS returns 404
=> OmsAgent OneClick fixes

VMEncryption/VMEncryption.pyproj, VMEncryption/main/BekUtil.py, VMEncryption/main/DiskUtil.py, VMEncryption/main/EncryptionSettingsUtil.py, VMEncryption/main/handle.py
1) We now stamp the VHDs which are encrypted instead of the OS disk
2) We now don't do detached LUKS headers 
3) We store the relevant line of azure_crypt_mount on a hidden folder on the encrypted device
4)We scan all attached devices when the extension is run and try to see if there any encrypted devices that are not in the azure_crypt_mount. If there are such devices we extract the lines from them and add them to the azure_crypt_mount file.
=> Code changes for VMSS reimage

OmsAgent/Fairfax/omsagent_ff.py, OmsAgent/omsagent.py
Added Debian 9 to the supported_dists.
Updated the hardcoded error_codes and placed in the header.
=> Enable debian9 & remove hardcoded extension errors

VMAccess/vmaccess.py
Parameter 'Uninstall' was being passed to hutil.do_parse_context()
inside the function install().
Signed-off-by: Eduardo Otubo <otubo@redhat.com>
=> Wrong parameter inside VMAccess

DSC/dsc.py
If the blob_name returned by parse_blob_uri contains a parent folder (IE: DSC/dscExtension.mof), then the get_blob_to_path call will fail due to the the parent path not existing (IE: /var/lib/waagent/Microsoft.OSTCExtensions.DSCForLinux-2.70.0.4/download/4/DSC) when the file is opened.  This change adds a check for the parent path, and creates it if it doesn't exist.
=> Blob storage download fails with parent folder

OmsAgent/watcherutil.py
This PR adds the 3 current DSC operation status files for collections by the OMS Agent extension telemetry.
The 3 DSC operations are:
- PerformRequiredConfigurationChecks
- PerformInventory
- SetDscLocalConfigurationManager
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/azure-linux-extensions/608)
=> Add DSC operation status files for telemetry

VMAccess/README.md
VMAccessForLinux makes a blanket check for reset based on the user setting a password.
If the return of this method is True, the SSH server will be reset.
Source code is here https://github.com/Azure/azure-linux-extensions/blob/master/VMAccess/vmaccess.py#L135 
And the same goes for check_disk – cf https://github.com/Azure/azure-linux-extensions/blob/master/VMAccess/vmaccess.py#L416
=> CRI 75202646 - some settings are mandatory

OmsAgent/omsagent.py
these failures are caused by something out of control of omsagent. Recover them once the SLA query by vmagent team excludes them
=> Modify error codes to exclude them from SLA failures

OmsAgent/watcherutil.py
This is in conjunction with the DSC PR: https://github.com/Microsoft/PowerShell-DSC-for-Linux/pull/418
Since the operation names have been shortened, this changes the status file names as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/azure-linux-extensions/616)
=> Shorten DSC operation names for OMS Agent telemetry

OmsAgent/watcherutil.py
This will fix DSC telemetry when an error occurs.
All new lines, tab characters, and quotes are now escaped from the message so that the message content will not affect the validity of the telemetry event JSON.
The operation status is also now ensured to be a lower case string since we were having some problems with the uppercase booleans in Python not being compatible with the lower case booleans of JSON.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/azure-linux-extensions/619)
=> Format telemetry event message and success strings for JSON

OmsAgent/omsagent.py
The 'suse': ('12') in supported_dists is not taken as a single '12' value instead it is treated as '1' & '2' while running it through the loop. 
Changing that to 'suse': ['12'] solves the issue. Just as a best practice, I've changed all the other supported_dists from string (' ') to list [' '].
=> correction make suse 12 included in supported_dists

OmsAgent/omsagent.py
Fix for - https://icm.ad.msft.net/imp/v3/incidents/details/92772102/home
IMDS does not have support for classic VMs. So the extension was failing at it when it could not get resource id.
=> OMS Agent: Allow installation when resource id is none

Utils/HandlerUtil.py, Utils/test/test_redacted_settings.py, VMAccess/vmaccess.py
For VMAccess, prevent protected settings from appearing in extension logs and config file.
=> Scrub protected settings from files and logs

Common/WALinuxAgent-2.0.16/waagent, CustomScript/customscript.py, CustomScript/manifest.xml, Utils/HandlerUtil.py, Utils/ScriptUtil.py
Seperating log to console vs log to file;
This is for the new requirement for which some extension output should not be logged to console (but only  to file).
This refactor also includes changes to CSE to log script output to file but not to console.
=> Seperating log to console vs log to file for CSE

VMEncryption/MANIFEST.in, VMEncryption/extension_shim.sh, VMEncryption/main/Common.py, VMEncryption/main/Utils/HandlerUtil.py, VMEncryption/main/check_util.py, VMEncryption/main/handle.py, VMEncryption/main/oscrypto/centos_68/encryptstates/StripdownState.py, VMEncryption/main/oscrypto/rhel_68/encryptstates/StripdownState.py, VMEncryption/main/oscrypto/ubuntu_1404/encryptstates/StripdownState.py, VMEncryption/main/oscrypto/ubuntu_1604/encryptstates/StripdownState.py, VMEncryption/setup.py, VMEncryption/test/test_check_util.py
- add extension shim for early exit if python 2.7 is unavailable on target system
- move archive to disable so future versions can restore in update
- improve restore performance by replacing slower shutil.copy2 with cp wildcard copy
- update various exit points with telemetry specific exit codes
- reduce enable failures by failing early on lvm os validation instead of warning
=> ADE SP Jan QOS

VMEncryption/main/BekUtil.py, VMEncryption/main/Common.py, VMEncryption/main/DiskUtil.py, VMEncryption/main/KeyVaultUtil.py, VMEncryption/main/handle.py, VMEncryption/test/test_check_util.py
1. Fix the disk util disk enumeration error
2. Fix the BEK Mounting permissions
3. Remove KV response logging line
=> Fix Disk Util and Bek Disk Mounting

VMEncryption/main/oscrypto/OSEncryptionStateMachine.py, VMEncryption/main/oscrypto/centos_68/CentOS68EncryptionStateMachine.py, VMEncryption/main/oscrypto/rhel_68/RHEL68EncryptionStateMachine.py, VMEncryption/main/oscrypto/rhel_72/RHEL72EncryptionStateMachine.py, VMEncryption/main/oscrypto/rhel_72_lvm/RHEL72LVMEncryptionStateMachine.py, VMEncryption/main/oscrypto/ubuntu_1404/Ubuntu1404EncryptionStateMachine.py, VMEncryption/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py
Some distros like RHEL & CentOS are not able send VMRestartPending
status to the portal. This seems to occur due to agent not working
properly in pivot root env. As a result, the extension is not
completing as customer don't know to restart the VM due to lack
of notification.
In this fix a rebbot is added at the end of encryption. This
will remove the need of manual restart by the customer.
=> Automatically restart VM after dual pass encryption completes.

OmsAgent/watcherutil.py
This file is going to include telemetry messages from the incoming omsconfig host (when OMI dependency is removed from omsconfig).
=> Add omsconfig host telemetry file path

VMEncryption/main/SupportedOS.json, VMEncryption/main/check_util.py, VMEncryption/main/handle.py, VMEncryption/main/patch/AbstractPatching.py, VMEncryption/setup.py, VMEncryption/test/test_check_util.py
Added a new json file that contains Distro, Version and Kernel information for supported OS encryption.
This file will be referred before starting a new enable operation.
=> Check if OS encryption is supported for Distro,Version and Kernel

VMEncryption/main/Common.py, VMEncryption/main/oscrypto/ubuntu_1604/encryptstates/PatchBootSystemState.py, VMEncryption/main/oscrypto/ubuntu_1604/encryptstates/SplitRootPartitionState.py
Porting Shiv's fix for None type has no getFlag method on Ubuntu 16.04 to dual pass.
=> Fix getFlag error on Ubuntu 16.04

OmsAgent/Fairfax/omsagent_ff.py, OmsAgent/Mooncake/omsagent_mc.py, OmsAgent/omsagent.py
- sys.version.major is not available in versions <2.7
- output message to stdout which waagent picks up
=> fix for python 2.6 break and writing to stdout

OmsAgent/omsagent.py
- Exit code 9 should be 52, because customer is calling enable before finishing install
=> Handle Exit code 9 

Diagnostic/DistroSpecific.py, Diagnostic/diagnostic.py
Python 2.7 doesn't recognize SUSE 15 since it was released before the distro. Fall-back /etc/os-release to detect.
=> LAD: SLES and OpenSUSE 15 distro support

OmsAgent/omsagent.py
- don't log to STDOUT for successful installs as its causing filtering in waagent log upload
=> Log to STDOUT only if exit code is not 0

VMEncryption/main/Common.py, VMEncryption/main/DiskUtil.py, VMEncryption/main/EncryptionSettingsUtil.py, VMEncryption/main/ResourceDiskUtil.py, VMEncryption/main/handle.py, VMEncryption/test/test_resource_disk_util.py
- Add a parser `crypttab`
- Add a post-reimage restore mechanism for `crypttab`
- Add methods to judge which unlock mechanism to use (old `azure_crypt_mount` vs `crypttab`)
- Unmount `BEK VOLUME` when it is needed to unmount `RD` (and then remount it again).
- Lint `handle.py` a little
=> Auto Unlock for ADE on new VMs

VMEncryption/main/Common.py, VMEncryption/main/DiskUtil.py, VMEncryption/main/ResourceDiskUtil.py, VMEncryption/main/handle.py, VMEncryption/test/test_resource_disk_util.py
- Add a parser crypttab
- Add a post-reimage restore mechanism for crypttab
- Add methods to judge which unlock mechanism to use (old azure_crypt_mount vs crypttab)
- Unmount BEK VOLUME when it is needed to unmount RD (and then remount it again).
- Lint handle.py a little
=> Auto Unlock for ADE on new VMs [Dual Pass]

VMEncryption/main/BekUtil.py, VMEncryption/main/DiskUtil.py, VMEncryption/main/handle.py
1. Remove new luks keys if update operation fails.
2. Remove reboot from singlepass update settings flow.
3. Commit encryption parameters after encryption settings are stamped.
4. Keep all passphrase files in sync when updating passphrase.
5. Fix multiple wireserver requests send by Linux extension.
=> Fix update encryption settings flow

Common/WALinuxAgent-2.0.16/waagent, VMAccess/manifest.xml
This PR adds Suse Linux 15 support for VMAccess extensions.
=> Suse Linux 15 support for VMAccess extensions

VMEncryption/main/Common.py, VMEncryption/main/check_util.py, VMEncryption/main/handle.py, VMEncryption/test/test_check_util.py
1. Created a new upper function to decide between enable and update flow
2. Handled the case when new disks needs to be encrypted in update flow.
3. Block enable if volume type transition is not allowed.
=> Update encryption settings fixes

OpenCensusAgent/opencensus-service/exporter/exporterwrapper/converterToApplicationInsights.go
Developer using this extension to send Open Census data to Application Insights does not need to add  instrumentation key for their resource. The key will be added when the Open Census data passes through the mdsd agent. In the future, "Tags" under Envelope will also be removed for the same reason.
@simathih
=> Remove instrumentation key

VMEncryption/main/handle.py
Do not start a daemon for query operation if encryption marker is not present.
=> Fix dual pass test failures

VMEncryption/main/DiskUtil.py
- use Python 2.6 compatible dictionary syntax in DiskUtil for CentOS 6.8 backcompat
=> ADE SP use 2.6 compatible dictionary syntax

VMEncryption/main/Common.py, VMEncryption/main/Utils/HandlerUtil.py, VMEncryption/test/test_handler_util.py
- equivalent to change recently merged to single pass extension
- adds error handling in the case of no settings file present when parsing context
- adds a unit test around disable to cover this scenario since a failure in disable can block update
=> ADE DP improve error handling when no settings file present

VMEncryption/main/DiskUtil.py
- use Python 2.6 compatible dictionary syntax in DiskUtil for CentOS 6.8 backcompat
=> ADE DP use 2.6 compatible dictionary syntax

AzureMonitorAgent/HandlerManifest.json, AzureMonitorAgent/README.md, AzureMonitorAgent/agent.py, AzureMonitorAgent/manifest.xml
By default, the -r/--remove flag in dpkg doesn't remove the config files (for ex. /etc/default/mdsd ) And we want the file to be replaced with the new installation. 
Thus adding the -P (--purge) flag to completely remove the configs related to mdsd so that the new version can create a fresh copy
Also adding checks before adding the MCS export vars statements (In case of Debian systems, if --install operation is ran multiple times, it will keep appending to the same file, Doesn't happen in RedHat systems as rpm prevents from installing the same package)
=> Using Purge to uninstall with dpkg and adding checks for MCS vars

Diagnostic/Utils/lad_logging_config.py, Diagnostic/tests/test_lad_logging_config.py
The state directory is a symlink to the primary workspace; which is different than LAD workspace. If VM is disjoined from primary workspace; the buffer path will turn invalid.
=> Move LAD's out_mdsd buffer path to own directory

VMEncryption/main/patch/centosPatching.py
adds python-six for CentOS 6.8 compatibility, required by transitions
=> ADE DP - add python-six for CentOS 6.8 compatibility

VMEncryption/main/patch/centosPatching.py
adds python-six for CentOS 6.8 compatibility, required by transitions
=> ADE SP - add python-six for CentOS 6.8 compatibility

.pipelines/pipeline.user.linux.all_buildtype.ade.yml, .pipelines/pipeline.user.windows.all_buildtype.ade.yml, VMEncryption/cdpx_windows_copy.cmd
Current CDPx Linux build implementation does not push artifacts automatically over to CloudVault but the Windows build does. OneBranch team suggested to workaround this problem by introducing a second build phase as a dummy Windows build which takes artifacts from the Linux build phase, binplaces them by a simple local copy, and automatically copy them over to CloudVault.
- Removed manifest.xml placing since it is already in the ZIP file.
- Removed an additional folder in the drop location.
=> Second CDPx build stage which uses Windows build to push artifacts to CloudVault.

OmsAgent/HandlerManifest.json
Adding continueOnUpdateFailure flag to the HandlerManifest.json (This was included in Fairfax release but never added to the code, this flag allows us to conitnue update of the extension in case the current version is in a failed state or doesn't get disabled)
=> adding continueOnUpdateFailure tag to HandlerManifest

Diagnostic/Utils/lad_logging_config.py, Diagnostic/lad_config_all.py
This flag is for syslog table only. It is useful when shipping syslog via eventhubpublisher, and don't need/want to duplication in Azure storage table
Fixes #944 
Signed-off-by: Sneha Nagendra <snnagen@microsoft.com>
=> [LAD] Add flag to disable storage account requirement

.gitignore, Common/WALinuxAgent-2.0.16/waagent
With newer distros coming up in Azure, some of the extension scenarios are failing because of the failing GetMyDistro() call, which gives a bad extensions experience to those VMs. I add a new DefaultDistro scenario which could help in preventing such scenarios and try to present a better user experience  in such cases.
Also update gitignore to prevent venv, pycharm and mac os files to be committed.
=> Support for newer distros by adding default distro; gitignore updated

VMBackup/main/ExtensionErrorCodeHelper.py, VMBackup/main/common.py, VMBackup/main/handle.py
Currently, this new error code doesn't come up as extensionErrorCode in BCmbackupStats. As I got to know, for it to show as ExtensionerrorCode in BCMbackup stats, this error Code with the same enum number value has to be present in the Status Codes in windows extension, that error code is already there. So I assume no other changes are required in the linux extension for the same. Please let me know if it is otherwise.
=> Avoiding leaked snapshots 

OmsAgent/omsagent.py
Added the optional parameter value for EX region for future deployments. The current EX deployment for 1.12.* **will follow the same format as the current Fairfax deployment to maintain parity and not this change.** 
This change can take effect from 1.13.* releases to FF/MC/EX onwards
=> Adding the endpoint for EX Cloud for omsagent,py

.gitmodules, OmsAgent/omsagent.py, OmsAgent/omsagent_shim.sh, OmsAgent/packaging.sh
- Original approach of using package managers to install python-future is not viable (package is not hosted in standard RPM repos), neither is using pip to install future (same reason, installing even pip is not straightforward/reliable).
- Instead, let's add python-future as a submodule. When we create the extension zip with `packaging.sh` the source files will be copied to `./ext/future`, which we add to PYTHONPATH.
=> Add python-future as a submodule

VMEncryption/main/patch/centosPatching.py, VMEncryption/main/patch/redhatPatching.py
Older RHEL distros does not seem to have cryptsetup-reencrypt package by default. It leads to extension trying to download them. When yum is run for the first time it does some configuration before downloading and installing the package. Hence, it exceeds the original 30 sec timeout. Increased the timeout to 100 sec to account for yum configuration.
=> Increase timeout for package installation.

Utils/distroutils.py, Utils/extensionutils.py, VMAccess/manifest.xml, VMAccess/vmaccess.py
IOError is an alias for OSError in python3, the code was written with that expectation. They don't overlap in python 2.
Changed all OSError to EnvironmentError to fix the issue.
EnvironmentError is the parent class for OSError and IOError in python 2. In python 3 IOError and EnvironmentError are both aliases to OSError.
=> Hotfix for ovf-env.xml for IOError in python2

VMAccess/manifest.xml, VMAccess/vmaccess.py
The following PR proposes a change to how backups of `sshd_config` are performed. Specifically, the following is being done:
* `copy2` is being leveraged in order to preserve original ownership and file metadata.
* An additional `chown` is being performed to make sure that the original owner and group are preserved.
The method `_backup_sshd_config` is called in a couple of cases: resetting the SSH configuration, or changing any user's password. In particular, this was being triggered while updating a user via the Azure CLI (`az vm user update ...`). The way current backups are being performed with `copyfile` does preserve the _contents_ of the configuration, however it doesn't preserve any specific permissions made to the configuration. In the cases of some OS configurations (e.g. CentOS …
=> `sshd_config` Backup Permission Preservation

AzureMonitorAgent/agent.py
1) VMs with CentOS 6, RHEL 6, Oracle 6 don't have systemctl and thus are unable to run mdsd service. Added support to run mdsd binary as a process and storing the pid in a file to later kill the process during disable. 
2) Switched to set([...]) instead of {}  as py 2.6 doesnt support the later simpler way of set instantiation.
=> Adding support for non systemd distros and fixing python set bug

OmsAgent/omsagent.py
- Add CentOS 8 and Ubuntu 20.04 to allowlist
- Update allowlist and tweaked manual distro parsing to ensure that newer distros (where `platform.linux_distribution()` and `platform.dist()` are deprecated) are correctly detected
- Fixed a corner case bug (that affected SLES 15.1+ in particular due to broken/missing `xml` module, but really any distro) where a failure to import waagent/handler utils would lead to a fallback on a faulty re-implementation of waagent `RunGetOutput`.
=> [OMS] Distro Allowlist & Encoding Fix

OmsAgent/omsagent.py
ICM 199803027
- Use proper log function that checks whether HUtil is None
- `telemetry()` function is actually not used (notice no entry in `HandlerManifest.json`, no other extensions have this); I think this was an unfinished feature either on GA side or Shrirang left before it was finished. In any case here I added another None check to make sure we don't hit an exception. Ideally we would make some proper handling of that case, but since `telemetry()` isn't used I want to minimize changes here.
=> OMS HUtil None Check

OmsAgent/omsagent.py
Currently OMS will attempt to query the IMDS endpoint on Arc machines, timing out after 2+ minutes. This change checks if the machine is an Arc machine, and then if so, instead queries the Arc IMDS endpoint.
=> Update IMDS Endpoint to work for Arc machines

AzureMonitorAgent/agent.py
When customer install AMA with auto_config flag we don't set the LA and default because most 1p customer will use mdsdmgrctl to deploy their tenants.
But i still don't know if there is a scenario where we need to setup default mdsd with Auto-Config env variable. @canfikret any input on this ?
=> Support auto-config mode

LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py, LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py
The current metrics code overwrites the existing config files (which are individually written per module) but doesn't clear them prior to onboarding. Due to this, in the edge case where cx removes every field of a particular module (mem, cpu, net etc), the config parser doesn't create a config for that module and thus the older config file for that module doesn't get cleared and telegraf reads them. **Telegraf does filter out these additional modules while sending data to mdsd but sends all of the modules (old and new) to ME. This change fixes that issue.**
Tests - 
Tested this alongside LAD 4.0 tests in all supported distros. This code is shared between AMA and LAD so the tests are sufficient coverage for both. 
Note: This doesn't happen when the cx removes only some of the counters of a …
=> Removing older metrics config during onboarding

VMEncryption/main/ResourceDiskUtil.py, VMEncryption/main/handle.py, VMEncryption/main/test/test_resource_disk_util.py
This PR includes:
Verification of Resource disk existence prior enabling encryption on resource disk when using EncryptFormatAll. The encryptFormatAll operation used to fail as there was no check to verify whether resource disk exists before the encryption operation.
=> Adding Resource disk validation for encryptFormatAll

LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py
We saw an issue where telegraf's influxdb output plugin was logging error logs due to the event size increasing the default value of upd payload (512B).
The suggested solution in telegraf's github issues is to increase the udp_payload parameter for influxdb output  - https://github.com/influxdata/telegraf/issues/6622
Went on a call with the cx and tested with increasing the udp_payload value to 1024B which resolved the issue.
=> Setting default udp payload value for influxdb output

AzureMonitorAgent/HandlerManifest.json, AzureMonitorAgent/agent.py, AzureMonitorAgent/packaging.sh, AzureMonitorAgent/shim.sh, LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py, LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py
1) Followed the steps listed by Henry in his OMS py2/3 PR - #1012 . Initially followed the [guide ](https://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html#integer-division) and using the [futurize tool](https://python-future.org/automatic_conversion.html).  
2) Manually fixed quite a few issues that couldn't be ported with automation. 
3) Re-used OMSAgent's shim file for interoping with py2/3. Currently we are not installing python if it isnt there. 
4) Added python-future as a submodule and using it in the shim file during agent.py's execution
5) Also added the continueOnUpdateFailure flag in Handlermanifest.json file to make the extension installation process more stable (that flag allows waagent to override faulty installations when they're stuck in update-disable loop and …
=> AMA python2/3 interoperability 

Diagnostic/diagnostic.py, Diagnostic/lad_config_all.py
The portal UI team needs to have AzMonSink config in public. So we had moved the entire sinks config from protected to public. But a better design approach is to only move AzMonSink config in public as the other sinks config can have urls and secrets that are better left in protected.
=> Moving general lad sinks config back to protected from public. 

Diagnostic/diagnostic.py, Diagnostic/manifest.xml
It was a bug introduced by the LADMaster -> Master in mdsd branch. The latest mdsd version, when validating the config, looks for the default /var/run/mdsd directory to check if it exists or not. but that directory is only created when mdsd is run. So when LAD runs this check before mdsd is run, it fails. 
Also changing version in manifest.xml (this is only used for logging purposes and isnt automatically updated by cdpx as I had thought)
=> mdsd default run dir during config validation

OmsAgent/omsagent.py
Azure Stack in mooncake doesn't support IMDS, they filed an ICM, they need a way to skip domain retrieval from IMDS and use the one passed from from settings.
=> Pass domain from protected settings

Diagnostic/lad_config_all.py
In the current design there is a flaw where LAD installation exits (telegraf setup throws exception) if it finds that there are no configs enabled for metrics. Adding a check before we create the telegraf configs to make sure not to pass invalid arguments.
=> Fixing install errors due to no metrics config

AzureMonitorAgent/agent.py
Setting protected settings for GCS auth to support AKV/dSMS cert rotation.
Fields: monitoringGCSAuthIdType, monitoringGCSAuthId
For testing you can set these values through protected settings and validate the value made it to /etc/default/mdsd
You should be looking for these: MONITORING_GCS_AUTH_ID_TYPE, MONITORING_GCS_AUTH_ID
=> Support adding GCS auth Id/type

VMBackup/main/fsfreezer.py
Tested with another processor taking lock and releasing it within timeout that is 34 sec(4 retries after 1 sec each and last retry after 30sec)
Logs:
================== Logs during Freeze Start ==============
2021/02/26 09:41:45.748281  Info  /etc/azure/MicrosoftRecoverySvcsSafeFreezeLock/SafeFreezeLockFile file opened Sucessfully
2021/02/26 09:41:45.748364  Info  Failed to open file or aquire lock:  [Errno 11] Resource temporarily unavailable
2021/02/26 09:41:46.749580  Info  Retry to aquire lock count: 1
2021/02/26 09:41:46.749825  Info  /etc/azure/MicrosoftRecoverySvcsSafeFreezeLock/SafeFreezeLockFile file opened Sucessfully
2021/02/26 09:41:46.749901  Info  Failed to open file or aquire lock:  [Errno 11] Resource temporarily unavailable
2021/02/26 09:41:47.750334  Info  Retry to …
=> Fsfreeze changes for file lock handling

VMEncryption/main/oscrypto/rhel_72_lvm/RHEL72LVMEncryptionStateMachine.py, VMEncryption/main/oscrypto/rhel_72_lvm/encryptstates/PatchBootSystemState.py
1. Don't make systemctl failure as hard failure in PatchBootSystem state
2. Force reboot if normal reboot doesn't work
3. Change is isolated RHEL 7 LVM where the crash is observed
=> Fix systemctl crash on RHEL LVM.

VMEncryption/main/handle.py, VMEncryption/main/test/test_disk_util.py, VMEncryption/main/test/test_encryption_config.py, VMEncryption/main/test/test_handler_util.py
Fixes python2/python3 compatibility issue that resulted in "invalid literal for int() with base 10:"
=> ADE SP fix for invalid literal

VMEncryption/main/patch/UbuntuPatching.py
- grub-pc-bin is a required package that has historically been present in all supported Ubuntu images 
- If removed as part of an update to the base image, its absence will break ADE scenarios 
- This additional check installs the package if needed
- The public facing documentation has also been updated to include this in the list of required packages: 
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-isolated-network#package-management
=> ADE SP add grub-pc-bin to install_extras

VMEncryption/main/CryptMountConfigUtil.py, VMEncryption/main/handle.py
-avoid TypeError on Python 3.x and support backwards compatibility with Python 2.7 by using a bytes-like object for comparison
=> use bytes type compare for p2/p3 compat

VMEncryption/main/patch/UbuntuPatching.py, VMEncryption/main/test/test_UbuntuPatching.py
- checks for presence of pre-installed packages on ubuntu, and skip if already installed
- better performance in mainline scenario when packages are present in base image
- better reliability when external package management servers are unavailable or within isolated networks
=> ADE SP add check for pre-installed packages to ubuntu patching

AzureMonitorAgent/agent.py
The goal of this change is to simplify the deployment by not having to pass the certificates as a parameter, but rely on an existing location under the provisioned VM.
This will allow to leverage the secrets option in the ARM template:
"secrets": [
{
"sourceVault": {
"id": "..."
},
"vaultCertificates": [
{
"certificateUrl": "..."
}
]
}
]
and reduce the need to manage the certificates externally by passing parameter like this:
"certificate": "file:/var/lib/waagent/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.crt",
"certificateKey": "file:/var/lib/waagent/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.prv"
=> Allow to use local path rather than passing the certificate and its key as parameter

AzureMonitorAgent/agent.py
Added logic to short circuit the enable() method when the [n].settings file in the config folder has not changed. 
The call to HandlerUtil.save_seq() stores the last sequence number that enable successfully ran for in mrseq. 
The check at the start of the function determines whether n (from most recent [n].settings file)> saved sequence number in mrseq before proceeding with enable()
=> AMA: short circuit enable() logic when sequence number has not changed

AzureMonitorAgent/agent.py
Adding cbl-mariner to the list of supported distros, to allow for AMA extension to install on Mariner for 1p.
=> Add Mariner to list of supported distros

OmsAgent/omsagent.py
Based off of the same change made in AMA: https://github.com/Azure/azure-linux-extensions/pull/1403
Added logic to short circuit the enable() method when the [n].settings file in the config folder has not changed.
=> OMS: short circuit enable() logic when sequence number has not changed

AzureMonitorAgent/agent.py, Diagnostic/diagnostic.py, LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py, LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py, OmsAgent/omsagent.py
It was reported that in some cases LAD may end up spawning numerous telegraf processes, leading to high resource consumption. This PR will address this by ensuring we
- Check for and stop previous telegraf processes before starting new one
- Do not start telegraf after Install and Enable both (should only happen for Enable); similarly remove redundant stop during Uninstall (already happens in Disable)
- When stopping telegraf, iterate through all PIDs that may be saved in the pidfile, in case there are multiple. Also, just read the `/proc/<pid>/cmdline` which seems simpler than making an `os.system` call, and is already well used in OMS/AMA wrappers.
263228506
=> Prevent telegraf duplicates

OmsAgent/omsagent.py
Added a logging statement to this specific case, to make it clearer when enable() exits early due to the seq number.
=> Clearer logging when exiting due to seq number

AzureMonitorAgent/agent.py, Diagnostic/diagnostic.py, LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py
- Fix implemented in mdsd codebase means agent proc can directly access `/var/opt/azcmagent/tokens/`, arc watcher proc is no longer necessary.
- Some misc issues surfaced by Pylance
=> Deprecate Arc watcher

AzureMonitorAgent/agent.py, AzureMonitorAgent/shim.sh
On RHEL 8.0, fallback to use platform-python if a user-installed python version is not present on the machine.
=> Fallback to platform-python on RHEL 8.0

VMEncryption/main/Common.py, VMEncryption/main/DiskUtil.py, VMEncryption/main/EncryptionEnvironment.py, VMEncryption/main/EncryptionMarkConfig.py, VMEncryption/main/OnlineEncryptionHandler.py, VMEncryption/main/OnlineEncryptionResumer.py, VMEncryption/main/handle.py
Online encryption of data disk flow:
1. Unmount data volume and create encryption layer.
2. Update crypttab/fstab for the disk
3. Resume parallel encryption for the disks.
This PR is not on our dev branch.
The changes will be merged to dev branch when all the sub features are ready.
=> Enable Online Encryption for data disks.

AzureMonitorAgent/agent.py, OmsAgent/omsagent.py
- The configuration of the defaults file should occur during `enable()` not `install()`, otherwise subsequent enables with new configuration after initial install (e.g. to add a proxy) will have no effect.
- I believe we should be creating a **fresh defaults file each enable**, rather than updating/appending to an existing file. With the update/append model, we aren't actually applying the desired state, and bugs could occur (imagine user specifies a managed identity, but then wants to go back to using the default identity; with the update/append model, we will leave the `MANAGED_IDENTITY` variable set wrongly). It will incur a small penalty in that any addition to the `azuremonitoragent.default` file in the main repo will need to be reflected here.
- Use an `OrderedDict` to make the …
=> [AMA] Configure defaults in enable

AzureMonitorAgent/agent.py
Python2 does not return a write length (returns `None`) for `write()`.
=> [AMA] Remove write length check

AzureMonitorAgent/agent.py
Added code to check for aarch64 machines and replace the package bundle name. aarch64 packages are included in the /package directory in the build pipeline.
=> Arm64 support for AMA

AzureMonitorAgent/agent.py
In upgrade scenario, waagent will do old disable > new update > old uninstall > new install > new enable. When AMA package is uninstalled it takes the /etc/default/azuremonitoragent file with it. After we added the enable short-circuit in #1403 as well as the config-in-enable changes in #1453, the upgrade scenario broke because we skipped the defaults file creation. This fixes that issue by only short-circuiting the service restart steps.
=> [AMA] Move enable short-circuit to after defaults generation

AzureMonitorAgent/agent.py
UAI feature is not yet released, so no risk to remove param option. 
Removing this in 3P case to avoid customer confusion; SAI has an object id, but IMDS will not return a token for the SAI if an object id (even the object id of the SAI itself) is specified. The only way to get token for SAI is to make the "default" call when there is only SAI (no UAI) assigned to the machine. For UAI, customers can still use `client_id` and `mi_res_id` to specify the UAI they want used.
This does not remove the capability for 1P single or multitenant, which is configured otherwise (not through extension settings).
=> Remove object_id MI specifier in AMA

AzureMonitorAgent/agent.py
Mariner 2.0 changed their ID from "cbl-mariner" to "mariner", updating to allow for support.
=> Add Mariner 2.0 Support

AzureMonitorAgent/agent.py, AzureMonitorAgent/packaging.sh
This PR is related to changes made here - 
[Pull Request 5771163](https://dev.azure.com/msazure/One/_git/Compute-Runtime-Tux/pullrequest/5771163): Arm64 Metrics Extension
The pipeline will download both x86 and arm64 versions of ME and agent.py will determine which binary to use during installation.
=> Add support for Arm64 Metrics Extension

OmsAgent/README.md, OmsAgent/omsagent.py
This PR, exposes the optional skipDockerProviderInstall option to the extension Settings so that we can customer can disable container monitoring data collection.
=> Expose skipDockerProviderInstall option for the extension install

LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
the ME binary for arm64 looks for a config file with lower casing and is unable to send data to LAW without this change. Long-term fix involves changes on the ME side to deal with this scenario.
=> added change to config file for arm64 ME

AzureMonitorAgent/agent.py
Disabling attempts to start coreAgent and PA for arm64 until we have arm64 binaries from the pipeline agent team
=> Disable custom logs for arm64

AzureMonitorAgent/agent.py
AMA install on rhel8 initially does not create required symlinks and enable fails. Re-trying install creates the required symlinks.
=> Fix for arm64 rhel8

AzureMonitorAgent/agent.py
The postinst script enables these services. This change explicitly disables and stops both these services for arm64 to prevent overly verbose error messages in syslog since we don't have CL support in arm64 yet.
=> arm64 - disable coreAgent and agentLauncher

AzureMonitorAgent/agent.py
Handle new schema format, while retaining back-compat (disallow mix-and-match). Example of new schema below.
`settings`:
```
{ 
"genevaConfiguration": { 
"enable": true 
}, 
"azureMonitorConfiguration": { 
"enable": true, 
"configuration": { 
"authentication": { 
"managedIdentity": { 
"identifier-name": "value", 
"identifier-value": "value" 
} 
}, 
"proxy": { 
"mode": "application", 
"address": "http://[address]:[port]", 
"auth": false 
} 
} 
} 
} 
```
`protectedSettings`:
```
{ 
"azureMonitorConfiguration": { 
"proxy": { 
"username": "[username]", 
"password": "[password]" 
} 
} 
} 
```
=> Handle new 1P/3P schema

OmsAgent/omsagent.py
A few changes:
1.  No longer log into stderror for intermediate status of command execution. This should prevent waagent reporting error while oms agent is still installing
2. Update the command output for some error cases to work with retry regex.
3. Lowered number of retries for install() to be 10 to prevent guest agent timeouts , and not occupying for long time.
4. fix curl error output for onboarding script.
=> fix retry install for package manager lock

AzureMonitorAgent/agent.py
I tested AMA 1.17.5 with these changes manually on Mariner 2.0, and was able to get logs to flow successfully. Adding official support for Mariner 2.0 for the next release of AMA.
=> Add Mariner 2.0 support to AMA

OmsAgent/omsagent.py
We need GPG to validate the signature of the bundle before it's installed, adding a check for GPG to try and install it if it doesn't exist.
In addition, adding Debian 10 support, as this is the only blocker for Debian 10 (data verified to flow without issue if GPG is on VM).
(Note: PR also made in shell bundle code to attempt to install GPG at shell bundle step, https://github.com/microsoft/OMS-Agent-for-Linux/pull/1460, but as GPG is needed to validate the signature before the shell bundle, we need to have this check here as well.)
=> Install GPG if not on VM + Debian 10 Support

AzureMonitorAgent/ama_tst/AMA-Troubleshooting-Tool.md
The original URL downloads the webpage the TST bundle is hosted on and puts it under the name of ama_tst.tgz, but under the hood it’s still a webpage. This would lead to an error stating the downloaded file was not in gzip format. Changing the URL to be the raw bundle itself.
=> Update typo in wget instructions

OmsAgent/omsagent.py
Some Debian 10 are slow installing gpg through guest agent cmdline interface. When RDPing to the machine it shows gpg is installed, but agent vm extension stays in connecting state. Changing this logic to log missing gpg eror, and ask customers to install gpg manually before attempting to install extension till root cause is determined, and more robust solution is found with testing more images.
=> [Abandoned] Skip gpg install if it is not available

OmsAgent/omsagent.py
Create dummy extension package that will always fail for debian VM. It is needed to test oms extension auto rollback feature and will be reverted right after pipeline creates extension package. This change will be deployed only in one canary region.
=> Extension auto rollback testing purpose only - should be reverted

OmsAgent/omsagent.py
This reverts commit bebe5bca62558557555a39a1f94a1732c41bf4e3 to recover from bad test build.
=> Revert "testing ext rollback purpose only-should be reverted (#1575)"

VMEncryption/main/oscrypto/rhel_81/encryptstates/PatchBootSystemState.py, VMEncryption/main/patch/AbstractPatching.py, VMEncryption/main/patch/marinerPatching.py, VMEncryption/main/patch/redhatPatching.py
Rather than using the standard dracut command for all distros and patching the initramfs for Mariner, these changes move repacking logic into distro specific scripts. Redhat based distros will now use dracut to create an initramfs, mariner uses mkinitrd.
=> Tweaking initrd/initramfs packing approach for Mariner

TestHandlerLinux/bin/disable.py, TestHandlerLinux/bin/enable.py, TestHandlerLinux/bin/update.py, TestHandlerLinux/installer/install.py, TestHandlerLinux/installer/uninstall.py, TestHandlerLinux/resources/HandlerUtil.py
This PR makes changes to strftime expressions, which are currently broken, including "minutes" twice instead of month/minute.
[Reference](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes)
=> Fix incorrect strftime expressions (fixes #1573)

Diagnostic/DistroSpecific.py
Note that Rocky 8 shows up as "Centos 8" according to how we check for distros (`platform.dist()`).
All 4 distros have been tested and confirmed to have data flowing, assuming python2 has been installed and aliased to `python` (noted in our docs already).
=> Add Support for Redhat 8, Rocky 8, AlmaLinux 8, and Centos 8

Diagnostic/services/metrics-extension.service, LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
Changes to ensure that Azure CIS-hardened image with AMA deployed still meets the pre-AMA benchmark score and does not cause the system to become out of compliance with the CIS benchmark. In this case, ME was listening on all interfaces, because if you don't specify the host, it will listen on 0.0.0.0. This was causing us to fail a benchmark rule requiring non-local ports to have iptables rules associated. With this change we ensure ME is only opening a port on localhost interface.
- Set `InfluxDbHost` to prevent CIS benchmark violation `3.4.3.2.3 Ensure iptables rules exist for all open ports`
=> AMA CIS hardening

VMEncryption/mdc-recommendation/helper-scripts/ImdsHelper.py, VMEncryption/mdc-recommendation/helper-scripts/MdcHandler.py, VMEncryption/mdc-recommendation/helper-scripts/VerifyVMSupport.py
- Updates to recognize Confidential VMs as NotSupported in the MDC recommendation for ADE + HBE.
- IMDS metadata is being used to detect the presence of CVM security type in VM profile.
- All CVMs will be categorized as NotSupported until data disk encryption is supported in CVMs.
=> Adding CVM detection to MDC recommendation

VMBackup/main/hostsnapshotter.py
Timezone and timestamp() do not work on older versions of python. Removed this dependency.
References:
1. https://pynative.com/python-datetime-to-seconds/
2. "int" and "long" unified in python version 2.2+ https://peps.python.org/pep-0237/
=> Fixing the dependency on timezone attribute

VMBackup/main/Utils/SizeCalculation.py, VMBackup/main/handle.py
Updating The logic to include the LogicalVolumes as well for billing, if the corresponding disks are included by the customer.
If the LogicalVolume is spread across disks that are not included, then billing for that volumes will not be done.
As customer can't be overbilled
Also includes the correction of the Existing Bug which reports the totalSize to be zero even after computation in handle.py for UnmanagedVm
=> LogicalVolumesInclusion

Common/WALinuxAgent-2.0.16/waagent
Fix python syntax warning found in AMA Install telemetry showing that agent is logging in standard error stream.
Example from AMA install telemetry:
[stderr]
Running scope as unit: install_52ef8942-a5b1-459d-b201-5ca1bfb45c60.scope
/var/lib/waagent/Microsoft.Azure.Monitor.AzureMonitorLinuxAgent-1.24.2/waagent:2578: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if me.returncode is not 0 and chk_err is True and log_cmd:
=> fix python syntax warning in waagent

Utils/extensionutils.py
Logging instead of throwing an exception when events folder has over 1000 files
=> Removing exception when events folder has over 1000 files

AzureMonitorAgent/agent.py
Verified that AMA works on Amazon 2 Linux VMs installed via Arc, adding official support. In addition, currently if the OS isn't supported, the error message seen by the cx will be "The OS has neither rpm or dpkg" - added the VM support check in a few common unintuitive failure locations to make it clearer when the issue is due to an unsupported OS.
=> Add Amazon 2 Linux Support

VMEncryption/mdc-recommendation/helper-scripts/MdcHandler.py, VMEncryption/mdc-recommendation/helper-scripts/VerifyVMSupport.py
Added updates to mark VMs unsupported by ADE and HBE as Compliant. 
Previously, these VMs were reported as Non-Compliant along with a reason for why the machine is not supported. Currently, MDC's custom logic to detect unsupported scenarios does not categorize the VMs correctly. The updates are a temporary work around to unblock for Public Preview. 
Also, updated "Host Based Encryption" feature name to "EncryptionAtHost" to align with customer facing documentation.
=> MDC Recommendation updates for unsupported scenarios

VMBackup/main/freezesnapshotter.py
In the current implementation, flags present in IncludedDisks parameter are only looked at if custom settings are not null. 
The code path where the snapshot mode is set to host only when vmgs blob is found, or when ddSnapshotIdentifiers are present- is not reached if custom settings input from CRP is null. This set of code should be independent of CustomSettings and hence, should be outside of the if block.
Sample includedDisks input:
`"includedDisks":{"dataDiskLunList":[0],"isAnyDirectDriveDiskIncluded":null,"isAnyDiskExcluded":false,"isAnyWADiskIncluded":null,"isOSDiskIncluded":true,"isVmgsBlobIncluded":true}`
Changes made
1. Put the block of code independent of customSettings outside of the if block.
2. Re-organized the order in which the flags are checked by grouping based on …
=> Fix for the TVM/DD flag check bug by re-organizing the code

AzureMonitorAgent/agent.py
Create syslog watcher to monitor DCR changes for 3P to generate local syslog configs if syslog is enabled in DCR
No change for 1P, always generate local syslog configs as before.
=> Install/uninstall syslog local configurations based on syslog DCR

VMBackup/main/Utils/HostSnapshotObjects.py, VMBackup/main/common.py, VMBackup/main/guestsnapshotter.py, VMBackup/main/hostsnapshotter.py, VMBackup/main/parameterparser.py
Need for Change:
We want to control the new feature rollout and since the dynamic Config is not there at BHS side, by passing flags received from CRP to BHS and XStore, we are trying to have a controlled rollout.
Made changes in
common.py
HostSnapshotObjects.py
Initializing the settings received
guestsnapshotter.py
appending the headers with ttl flag
hostsnapshotter.py
Sending the settings as part of request body, when a call is made for DoSnapshot.
parameterparser.py
fetching the settings passed from CRP and validating them with known setting flags.
=> Send Flags via Request To BHS, Xstore

AzureMonitorAgent/agent.py
Fixed typo in Boolean value: The lowercase *true* is not a valid identifier in python. This will use the proper *True* instead.
Fixes #1749
=> Using Boolean True instead of true

AzureMonitorAgent/agent.py
Fix the bug that python 3.8+ doesn't have function platform.linux_distribution() and platform.dist(), and manaul parsing doesn't catch 'ol' as a supported distro.
=> Add 'ol' as a valid distro name

AzureMonitorAgent/agent.py
Had customer issue where 'sles' 12.4/12.5 were saying not supported, despite being validated and supported distros. Above check only verifies for 'suse' 12.4, despite suse/sles being the same distro. Fixed this so 'suse'/'sles' are interchangeable.
=> Fix Check for Suse/SLES Distros

AzureMonitorAgent/ama_tst/modules/connect/connect.py, AzureMonitorAgent/ama_tst/modules/helpers.py
Before the fix: 
If perf counters are not enabled, the tool crashes with "'FileNotFoundError' is not defined". Output log when running the tool with option2:
Please select an option: 2
--------------------------------------------------------------------------------
The troubleshooter can be run in two different modes.
- Silent Mode runs through with no input required
- Interactive Mode includes extra checks that require input
Do you want to run the troubleshooter in silent (s) or interactive (i) mode?: s
Running troubleshooter in silent mode...
================================================================================
CHECKING CONNECTION...
Checking AMA parameters in /etc/default/azuremonitoragent...
Checking DCR...
Traceback (most recent call last):
File "./modules/main.py", line …
=> fix ama troubleshooter to run option 2 with python 2.7

Utils/test/test_extensionutils_code_injection.py
mktemp() is insecure, updating to NamedTemporaryFile() which is identical in practice but more secure.
=> Change mktemp() to NamedTemporaryFile() in test_extensionutils_code_injection.py

.gitmodules, OmsAgent/omsagent.py, OmsAgent/omsagent_shim.sh, OmsAgent/packaging.sh, OmsAgent/watcherutil.py
This PR covers removal of 3rd party urllib dependency PythonCharmers that triggered s360 security bugs. We ll' be using python2 standard libs such as urllib and urlparse APIs moving forward.
Unit tested by mocking extension calls with distros running python v3.8.10, python 2.7.5.
=> remove python-future from oms extension

VMAccess/vmaccess.py
Azure 'reset password' feature overrides the /etc/ssh/sshd_config file and sets the PasswordAuthentication to 'yes'. Unfortunately, cloud-init versions 22.3 and newer sets 'PasswordAuthentication' to 'no' in the /etc/ssh/sshd_config.d/50-cloud-init.conf which overrides the setting in /etc/ssh/sshd_config file. VMAccess handles this for Ubuntu by setting PasswordAuthentication to 'yes' additionally in /etc/ssh/sshd_config.d/50-cloud-init.conf file. This change extends the same method to include CentOS and RHEL systems.
Fixes: https://github.com/canonical/cloud-init/issues/4335
=> Set password auth in 50-cloud-init.conf for CentOS and RHEL systems

AzureMonitorAgent/agent.py
Always executing _semanage port -a_ it creates additonal audit entries and load on Microsoft Defender.
Doing a test if is required allows reducing system load
=> Tests if execution of semanage is required. 

TestHandlerLinux/resources/mypydoc.py
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [mypydoc.py](https://github.com/Azure/azure-linux-extensions/blob/master/TestHandlerLinux/resources/mypydoc.py), there is a method that creates a temporary file using an unsafe API mktemp. The use of this method is discouraged in the Python [documentation](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp). iCR suggested that a temporary file should be created using `mkstemp` which is a [safe API](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp). iCR replaced the usage of `mktemp` with `mkstemp`.
In file `TestHandlerLinux/resources/mypydoc.py`, the method `mktemp` in line 1387 was replaced by `mkstemp`.
*This section is only relevant if your project requires …
=> Fixed an improper method call

VMEncryption/main/handle.py
This is to unblock tdx CVM until GA is fixed.
=> VMEncryption: For confidential VM temp disk enc, do not attempt secure key release if KEK is not provided

Diagnostic/Utils/LadDiagnosticUtil.py, Diagnostic/diagnostic.py
If configuration had no metrics or perf counters set up to be collected, telegraf would (rightly) not be installed, but LAD's code would repeatedly try to start up telegraf every 30 seconds (and log the failure to extension.log). This fixes this bug to check if telegraf should be enabled based on the configuration.
Specifically, if there is a metrics section but no `scheduledTransferPeriod` value (and no perf counters section), our previous behavior was to try and set up metrics for PT1H and start telegraf, which wouldn't succeed as telegraf was never installed initially. This change lines us up with [our current public docs](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/diagnostics-linux?toc=%2Fazure%2Fazure-monitor%2Ftoc.json&tabs=azcli#metrics), which clarify that …
=> Fix Telegraf not starting errors

AzureMonitorAgent/agent.py
Fix Bug: https://msazure.visualstudio.com/One/_workitems/edit/25769885/
This package is unused from 4 years ago. From static analysis and manual inspection, I didn't find any version related function uses this class.
=> Remove unused package

AzureMonitorAgent/HandlerManifest.json, AzureMonitorAgent/packaging.sh
`json_pp` and `jq` both present in mariner build container for extension packaging step. per some research, json_pp has more helpful error messages and tends to be stricter / closer to JSON spec when validating. Example with previously-incorrect HandlerManifest.json:
> , or } expected while parsing object/hash, at character offset 583 (before ""cpuQuotaPercentage"...") at /usr/bin/json_pp line 59.
=> Fix AMA HandlerManifest.json syntax

VMEncryption/main/Common.py, VMEncryption/main/oscrypto/ubuntu_2004/encryptstates/EncryptBlockDeviceState.py, VMEncryption/main/oscrypto/ubuntu_2004/encryptstates/PatchBootSystemState.py
This PR fixes below issues:
1. OS encryption failure on Ubuntu 22
For some reason, blkid or lsblk is not returning root partition's PARTUUID at the time we request it. The cause is still unclear.
Updated the logic to not rely on the command ans use partuuid symlinks to get root partition's PARTUUID.
2. XFS module corruption after OS disk encryption on Ubuntu 22
conv=sparse and bs=64K seems to be skipping some required blocks encryption causing the module corruption.
Update bs to 16M so that blocks are not skipped.
=> Fix Ubuntu 22 xfs and partuuid errors.

VMEncryption/mdc-recommendation/cpp/AzureLinuxVMEncryptionCompliance/LinuxEncryptionCompliance/LinuxEncryptionCompliance/CMakeLists.txt, VMEncryption/mdc-recommendation/cpp/AzureLinuxVMEncryptionCompliance/LinuxEncryptionCompliance/LinuxEncryptionCompliance/LinuxEncryptionCompliance.cpp, VMEncryption/mdc-recommendation/cpp/AzureLinuxVMEncryptionCompliance/LinuxEncryptionCompliance/LinuxEncryptionCompliance/nlohmann/json.hpp
Removing boost dependency from the LinuxEncryptionCompliance resource. This is required to unblock upgrades to the GC agent.
=> Remove boost dependency LinuxEncryptionCompliance

AzureMonitorAgent/agent.py
Add Debian 12 support
Debian 12 does not have rsyslog by default, install rsyslog if not present
=> add debian12 support

VMEncryption/main/check_util.py
adding SKR attestation traces for failure in SKR.
=> adding to log traces, set env SKR_TRACE_ON for failed cases

VMEncryption/main/SupportedOS.json, VMEncryption/main/Utils/waagentloader.py, VMEncryption/main/oscrypto/91adeOnlineUbu/crypt-ade-boot, VMEncryption/main/oscrypto/91adeOnlineUbu/crypt-ade-hook, VMEncryption/main/oscrypto/OSEncryptionState.py, VMEncryption/main/oscrypto/rhel_81/encryptstates/PatchBootSystemState.py, VMEncryption/main/patch/AbstractPatching.py, VMEncryption/main/patch/UbuntuPatching.py, VMEncryption/main/patch/marinerPatching.py, VMEncryption/main/patch/redhatPatching.py, VMEncryption/setup.py
Ubuntu now has sperate boot partition that enables ADE to onboard it to online encryption path. 
Currently tested with Ubuntu 23.10.
=> Onboard Ubuntu 24.04 to online encryption and add support for RHEL 9.3

VMEncryption/main/check_util.py
In last commit, it is forced to user for providing MSI id even VM associated with only one MSI. 
MSI must be provided if VM is associated with multiple identities. If VM associated with single identity providing MSI information in public setting is optional.
=> If VM does associated with single MSI, then don't force to provide in public setting

VMEncryption/main/patch/redhatPatching.py
Boot filesystem mount failure on RHEL 9 ( >= 2.06-69) after enabling ADE feature on a VM. 
The VM will not boot and the serial console log shows that ADE tried to update BLS cmdline with grub2-mkconfig to add rd.luks.ade.partuuid and rd.luks.ade.bootuuid parameters.
=> Update bls cmdline if grub2 version is greater than 2.06.69

VMBackup/main/hostsnapshotter.py
This PR is regarding fix of Compatibility Issue with total_seconds() for python version <=2.6
There was a compatibility issue of total_seconds() whith python version < = 2.6, so updated it to use timedelta which is compatible for all versions of Python, including Python 2.6, 2.7, and 3.x. New implementation utilizes total_seconds() method if available, otherwise falls back to custom implementation that converts it using custom logic to calculate elapsed seconds (delta.days * 86400 + delta.seconds + delta.microseconds / 1e6)
=> Fixed Compatibility issue with timestamp.total_seconds() method for python version <=2.6

VMBackup/main/Utils/HandlerUtil.py, VMBackup/main/Utils/LogHelper.py
In few customer VMs, on upgrading VMSnapshotLinux extension version, the older status files are copied and are not getting cleared out. Added a utility function to clear out stale files in any given directory, with a given extension and file# limit.
=> Clear old settings and status files

AzureMonitorAgent/agent.py
Fix for bug 29033303 to accept object_id in supported identifier-name for managed identity. 
Testing: Ran uninstall (./shim.sh --disable and ./shim.sh --uninstall) and then install (./shim.sh --install and ./shim.sh --enable) using the updated agent.py on a VM with AMA. Didn't see any error in logs (extension and azuremonitoragent) and installation was successful.
=> Adding object_id to supported identifier-name for managed identity

AzureMonitorAgent/agent.py, LAD-AMA-Common/metrics_ext_utils/metrics_ext_handler.py
we have seen a few incidents (Arc and Cloud) where due to hardening or firewall rules customer used to see failure from python code but not able to determine the actual url that ama is querying  post ama auto upgrade/during enable calls. With this change ama will  log imds url info for easy troubleshooting.
=> log imds url to improve diagnosability

VMBackup/main/ExtensionErrorCodeHelper.py, VMBackup/main/Utils/HandlerUtil.py, VMBackup/main/common.py, VMBackup/main/freezesnapshotter.py
In Linux Extension code, 500 status code from the DoSnapshot API response from BHS was incorrectly converted to a client error in both the Extension and CRP. This caused the error to be misclassified, preventing early detection via LSI.
Example Response:
2024-10-22 22:49:39.187634  Info  dosnapshot responseBody: StatusCode:500, ErrorMessage: Could not find config corresponding to the Disk  - md-zt1h5xp3fb3q - 4gsgxhsfkwl2/abcd, bhsVersion:3.0.51.0  
Incorrect conversion in Extension:
{"Key": "extErrorCode", "Value": "FailedRetryableSnapshotFailedNoNetwork"}
Fix:
Updated the Extension code to correctly classify 500 responses from DoSnapshot API as BHS error instead of client errors.
=> Fix incorrect conversion of DoSnapshot API 500 response to client error in Extension

AzureMonitorAgent/agent.py
NET files are not used anymore, but when the files are left on the system they cause AOT runtime issues. Reproducible when the machine upgrades from old version of ama extension to the new one. This is caused by a bug in ama uninstall where package manager leaves some ama folders behind.
=> cleanup old installer.net runtimes in extension upgrade path left behind in uninstall causing aot runtime issues 

LAD-AMA-Common/telegraf_utils/telegraf_config_handler.py
Fix pylint [E0606] error (possibly-used-before-assignment) for urllib
=> Fix pylint [E0606] error (possibly-used-before-assignment)

AzureMonitorAgent/agent.py
This pull request enhances the `find_vm_distro` function in `AzureMonitorAgent/agent.py` to improve the detection of Linux distributions by parsing distribution-specific files directly. The changes prioritize reliability and expand support for detecting various distributions, including fallback mechanisms for less common cases.
* **Direct parsing of `/etc/os-release` for modern distributions:** The function now reads and parses `/etc/os-release` to detect the distribution and version, including fallback mechanisms using `ID_LIKE` for vendor-specific suffixes. Remove dependency on the python `platform` module
* **Support for additional files:** Added checks for `/etc/system-release`, `/etc/SuSE-release`, `/etc/redhat-release`, `/etc/lsb-release`, and `/etc/debian_version` to detect …
=> Improve Linux AMA distro detection

AzureMonitorAgent/ama_tst/__init__.py, AzureMonitorAgent/ama_tst/modules/__init__.py
add init.py to ama_tst folders for python2.7 to pick up the supported distros submodule
=> add init.py to ama_tst folders for python2.7

AzureMonitorAgent/agent.py
Implemented AMA package version detection to be used in `install()` and `uninstall()` while improving diagnostic logging to provide more information on multiple AMA package scenario. For RPM, we attempt to uninstall each package name specifically, followed by the `--allmatches` flag followed by `--noscripts --nodeps`.
=> Revised Install() and Uninstall() for agent.py
